/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * <a href=\"https://guide.itscope.com/kb/zubehoer-typen/\">Originalzubehör und kompatibles Zubehör</a> zu einem Produkt
 *
 * @param referencedProductId Referenz auf ein Bezugsprodukt, z.B. ein Produkt das als Originalzubehör geführt wird
 * @param typeId Interne Kennung für die <a href=\"https://guide.itscope.com/kb/zubehoer-typen/\">Art des Bezugsproduktes</a>
 * @param type Bezeichner für die <a href=\"https://guide.itscope.com/kb/zubehoer-typen/\">Art des Bezugsproduktes</a>, z.B. Original-Zubehör, Kompatibles Zubehör, usw.
 */


data class Accessory (

    /* Referenz auf ein Bezugsprodukt, z.B. ein Produkt das als Originalzubehör geführt wird */
    @get:JsonProperty("referencedProductId")
    val referencedProductId: kotlin.Long? = null,

    /* Interne Kennung für die <a href=\"https://guide.itscope.com/kb/zubehoer-typen/\">Art des Bezugsproduktes</a> */
    @get:JsonProperty("typeId")
    val typeId: kotlin.Int? = null,

    /* Bezeichner für die <a href=\"https://guide.itscope.com/kb/zubehoer-typen/\">Art des Bezugsproduktes</a>, z.B. Original-Zubehör, Kompatibles Zubehör, usw. */
    @get:JsonProperty("type")
    val type: kotlin.String? = null

) {


}

