/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param logClick 
 * @param apiVersion 
 * @param reportType 
 * @param formatTemplate 
 * @param qualifiedId 
 * @param openTransType 
 */


data class ApiViewType (

    @get:JsonProperty("id")
    val id: kotlin.String? = null,

    @get:JsonProperty("logClick")
    val logClick: kotlin.Boolean? = null,

    @get:JsonProperty("apiVersion")
    val apiVersion: ApiViewType.ApiVersion? = null,

    @get:JsonProperty("reportType")
    val reportType: kotlin.Boolean? = null,

    @get:JsonProperty("formatTemplate")
    val formatTemplate: kotlin.String? = null,

    @get:JsonProperty("qualifiedId")
    val qualifiedId: kotlin.String? = null,

    @get:JsonProperty("openTransType")
    val openTransType: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: V10,V20,V21
     */
    enum class ApiVersion(val value: kotlin.String) {
        @JsonProperty(value = "V10") V10("V10"),
        @JsonProperty(value = "V20") V20("V20"),
        @JsonProperty(value = "V21") V21("V21");
    }

}

