/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import de.itscope.api.dto.AttributeUnit

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Konkrete Eigenschaftstypen von Produkteigenschaften.
 *
 * @param attributeUnit 
 * @param id Eindeutige Kennung eines konkreten Eigenschafttyps
 * @param name Name des konkreten Eigenschafttyps
 * @param rank Ranking des Eigenschafttyps, kann z.B. zur Sortierung verwendet werden
 * @param type <a href=\"https://guide.itscope.com/kb/datentypen-einzelner-eigenschaften/\">Datentyp</a> des Eigenschafttyps
 * @param groupId Kennung einer Eigenschaftsgruppe, kein Tabellenverweis, sondern identifiziert attributeTypeGroupName eindeutig
 * @param groupName Name der Eigenschaftsgruppe
 */


data class AttributeType (

    @get:JsonProperty("attributeUnit")
    val attributeUnit: AttributeUnit,

    /* Eindeutige Kennung eines konkreten Eigenschafttyps */
    @get:JsonProperty("id")
    val id: kotlin.Long? = null,

    /* Name des konkreten Eigenschafttyps */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Ranking des Eigenschafttyps, kann z.B. zur Sortierung verwendet werden */
    @get:JsonProperty("rank")
    val rank: kotlin.Long? = null,

    /* <a href=\"https://guide.itscope.com/kb/datentypen-einzelner-eigenschaften/\">Datentyp</a> des Eigenschafttyps */
    @get:JsonProperty("type")
    val type: kotlin.Int? = null,

    /* Kennung einer Eigenschaftsgruppe, kein Tabellenverweis, sondern identifiziert attributeTypeGroupName eindeutig */
    @get:JsonProperty("groupId")
    val groupId: kotlin.Long? = null,

    /* Name der Eigenschaftsgruppe */
    @get:JsonProperty("groupName")
    val groupName: kotlin.String? = null

) {


}

