/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Eigenschaftscluster, in denen das Produkt für Merkmalssuchen gefunden werden kann. Kann je nach Menge mehrere Eigenschaftsausprägungen in Intervallen zusammenfassen, z.B. 64-128MB RAM
 *
 * @param id Eindeutiger ITscope Key
 * @param productTypeId Referenz auf den Produkttyp, optional
 * @param productTypeName Name des Produkttyps, zu dem diese Eigenschaftsausprägung gehört, optional
 * @param attributeTypeName Name einer Eigenschaft. Kann analog dem Namen aus ProductType.attributeTypeName(1..5) sein
 * @param attributeTypeGroupName Name einer Eigenschaftsgruppe
 * @param name Bezeichner der Ausprägung (z.B. 2 GB, 15\", 80 W - 120 W)
 * @param rank Rang der Eigenschaft
 */


data class AttributeCluster (

    /* Eindeutiger ITscope Key */
    @get:JsonProperty("id")
    val id: kotlin.Long? = null,

    /* Referenz auf den Produkttyp, optional */
    @get:JsonProperty("productTypeId")
    val productTypeId: kotlin.Long? = null,

    /* Name des Produkttyps, zu dem diese Eigenschaftsausprägung gehört, optional */
    @get:JsonProperty("productTypeName")
    val productTypeName: kotlin.String? = null,

    /* Name einer Eigenschaft. Kann analog dem Namen aus ProductType.attributeTypeName(1..5) sein */
    @get:JsonProperty("attributeTypeName")
    val attributeTypeName: kotlin.String? = null,

    /* Name einer Eigenschaftsgruppe */
    @get:JsonProperty("attributeTypeGroupName")
    val attributeTypeGroupName: kotlin.String? = null,

    /* Bezeichner der Ausprägung (z.B. 2 GB, 15\", 80 W - 120 W) */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Rang der Eigenschaft */
    @get:JsonProperty("rank")
    val rank: kotlin.Long? = null

) {


}

