/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Eigenschaften zu einem Produkt.
 *
 * @param `value` Der Basiswert (siehe auch <a href=\"'https://guide.itscope.com/kb/einheiten-fuer-produkteigenschaften-vom-typ-zahl/\">Basiseinheit</a>) der Eigenschaft, bei Text als Textbaustein, bei Zahlen als kleinste Angabe
 * @param displayValue Der lesbare Wert der Eigenschaft, inklusive Einheit
 * @param attributeTypeId Eindeutige Kennung eines konkreten Eigenschafttyps
 * @param attributeTypeName Name des konkreten Eigenschafttyps
 * @param attributeTypeRank Ranking des Eigenschafttyps, kann z.B. zur Sortierung verwendet werden
 * @param attributeTypeGroupId Kennung einer Eigenschaftsgruppe, kein Tabellenverweis, sondern identifiziert attributeTypeGroupName eindeutig
 * @param attributeTypeGroupName Name der Eigenschaftsgruppe
 */


data class Attribute (

    /* Der Basiswert (siehe auch <a href=\"'https://guide.itscope.com/kb/einheiten-fuer-produkteigenschaften-vom-typ-zahl/\">Basiseinheit</a>) der Eigenschaft, bei Text als Textbaustein, bei Zahlen als kleinste Angabe */
    @get:JsonProperty("value")
    val `value`: kotlin.String? = null,

    /* Der lesbare Wert der Eigenschaft, inklusive Einheit */
    @get:JsonProperty("displayValue")
    val displayValue: kotlin.String? = null,

    /* Eindeutige Kennung eines konkreten Eigenschafttyps */
    @get:JsonProperty("attributeTypeId")
    val attributeTypeId: kotlin.Long? = null,

    /* Name des konkreten Eigenschafttyps */
    @get:JsonProperty("attributeTypeName")
    val attributeTypeName: kotlin.String? = null,

    /* Ranking des Eigenschafttyps, kann z.B. zur Sortierung verwendet werden */
    @get:JsonProperty("attributeTypeRank")
    val attributeTypeRank: kotlin.Long? = null,

    /* Kennung einer Eigenschaftsgruppe, kein Tabellenverweis, sondern identifiziert attributeTypeGroupName eindeutig */
    @get:JsonProperty("attributeTypeGroupId")
    val attributeTypeGroupId: kotlin.Long? = null,

    /* Name der Eigenschaftsgruppe */
    @get:JsonProperty("attributeTypeGroupName")
    val attributeTypeGroupName: kotlin.String? = null

) {


}

