/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Einheiten aller konkreten Eigenschaftstypen.
 *
 * @param id Eindeutige Kennung einer Einheit
 * @param baseUnitId Die <a href=\"'https://guide.itscope.com/kb/einheiten-fuer-produkteigenschaften-vom-typ-zahl/\">Basiseinheit</a> der Einheit
 * @param mulFactor Multiplikationsfaktor für die Umrechnung von Basiseinheit auf Einheit
 * @param divFactor Divisor für die Umrechnung von Basiseinheit auf Einheit
 */


data class AttributeUnit (

    /* Eindeutige Kennung einer Einheit */
    @get:JsonProperty("id")
    val id: kotlin.String? = null,

    /* Die <a href=\"'https://guide.itscope.com/kb/einheiten-fuer-produkteigenschaften-vom-typ-zahl/\">Basiseinheit</a> der Einheit */
    @get:JsonProperty("baseUnitId")
    val baseUnitId: kotlin.String? = null,

    /* Multiplikationsfaktor für die Umrechnung von Basiseinheit auf Einheit */
    @get:JsonProperty("mulFactor")
    val mulFactor: kotlin.Long? = null,

    /* Divisor für die Umrechnung von Basiseinheit auf Einheit */
    @get:JsonProperty("divFactor")
    val divFactor: kotlin.Long? = null

) {


}

