/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import de.itscope.api.dto.ReferencedAddresses

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param puid 
 * @param supplierId 
 * @param supplierItemId 
 * @param quantity 
 * @param comment 
 * @param customerOrderReference 
 * @param referencedAddresses 
 */


data class CartLineItemOrder (

    @get:JsonProperty("puid")
    val puid: kotlin.Long? = null,

    @get:JsonProperty("supplierId")
    val supplierId: kotlin.Long? = null,

    @get:JsonProperty("supplierItemId")
    val supplierItemId: kotlin.String? = null,

    @get:JsonProperty("quantity")
    val quantity: kotlin.Int? = null,

    @get:JsonProperty("comment")
    val comment: kotlin.String? = null,

    @get:JsonProperty("customerOrderReference")
    val customerOrderReference: kotlin.String? = null,

    @get:JsonProperty("referencedAddresses")
    val referencedAddresses: ReferencedAddresses? = null

) {


}

