/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import de.itscope.api.dto.CartLineItemOrder

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param cartLineItem 
 */


data class CartLineItemOrderContainer (

    @get:JsonProperty("cartLineItem")
    val cartLineItem: kotlin.collections.List<CartLineItemOrder>

) {


}

