/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import de.itscope.api.dto.Manufacturer
import de.itscope.api.dto.Supplier

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Jeder Hersteller oder Lieferant ist einer Firma zugeordnet
 *
 * @param name Name der Firma
 * @param street Straßenname der Hauptadresse der Firma
 * @param zip Postleitzahl der Hauptadresse der Firma
 * @param city Stadtname der Hauptadresse der Firma
 * @param country Land der Hauptadresse der Firma
 * @param manufacturer 
 * @param supplier 
 */


data class Company (

    /* Name der Firma */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Straßenname der Hauptadresse der Firma */
    @get:JsonProperty("street")
    val street: kotlin.String? = null,

    /* Postleitzahl der Hauptadresse der Firma */
    @get:JsonProperty("zip")
    val zip: kotlin.String? = null,

    /* Stadtname der Hauptadresse der Firma */
    @get:JsonProperty("city")
    val city: kotlin.String? = null,

    /* Land der Hauptadresse der Firma */
    @get:JsonProperty("country")
    val country: kotlin.String? = null,

    @get:JsonProperty("manufacturer")
    val manufacturer: Manufacturer? = null,

    @get:JsonProperty("supplier")
    val supplier: Supplier? = null

) {


}

