/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Vertragsparameter fürs Bestellen
 *
 * @param displayName Beschreibung des Vertragsparameters
 * @param orderParameterName Die Id des Vertragsparameters
 * @param mandatory Der Vertragsparameter ist bei der Bestellung ein Pflichtfeld
 * @param example Beispiel für den entsprechenden Vertragsparameter
 */


data class ContractParameter (

    /* Beschreibung des Vertragsparameters */
    @get:JsonProperty("displayName")
    val displayName: kotlin.String? = null,

    /* Die Id des Vertragsparameters */
    @get:JsonProperty("orderParameterName")
    val orderParameterName: kotlin.String? = null,

    /* Der Vertragsparameter ist bei der Bestellung ein Pflichtfeld */
    @get:JsonProperty("mandatory")
    val mandatory: kotlin.Boolean? = null,

    /* Beispiel für den entsprechenden Vertragsparameter */
    @get:JsonProperty("example")
    val example: kotlin.String? = null

) {


}

