/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * <a href=\"https://guide.itscope.com/kb/kategorien-fuer-content/\">ITscope-Kategorisierung</a> für Content (z.B. Strukturierte Merkmalstexte, Produktfoto,usw.).
 *
 * @param id Eindeutiger Key
 * @param name Bezeichner der Kategorie
 */


data class ContentCategory (

    /* Eindeutiger Key */
    @get:JsonProperty("id")
    val id: kotlin.Long? = null,

    /* Bezeichner der Kategorie */
    @get:JsonProperty("name")
    val name: kotlin.String? = null

) {


}

