/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * <a href=\"https://guide.itscope.com/kb/modell-fuer-content/\">Einteilung der Contents in unterschiedliche Typen durch den Contentanbieter.</a>,
 *
 * @param id Eindeutiger Key
 * @param name Anzeigename des Contents (z.B. Icecat Standardbild groß, 1WorldSync Produkt-ID)
 */


data class ContentModel (

    /* Eindeutiger Key */
    @get:JsonProperty("id")
    val id: kotlin.Long? = null,

    /* Anzeigename des Contents (z.B. Icecat Standardbild groß, 1WorldSync Produkt-ID) */
    @get:JsonProperty("name")
    val name: kotlin.String? = null

) {


}

