/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * <a href=\"https://guide.itscope.com/kb/provider-fur-content/\">Herkunft des Content</a> z.B. 1WorldSync, Icecat, Hersteller, Distributor
 *
 * @param id Eindeutiger Key
 * @param name Klartextname des Contentlieferanten (z.B. Icecat, DCI)
 * @param rank Priorisierung, zur Sortierung, gleiche Werte mehrfach möglich
 */


data class ContentProvider (

    /* Eindeutiger Key */
    @get:JsonProperty("id")
    val id: kotlin.Long? = null,

    /* Klartextname des Contentlieferanten (z.B. Icecat, DCI) */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Priorisierung, zur Sortierung, gleiche Werte mehrfach möglich */
    @get:JsonProperty("rank")
    val rank: kotlin.Int? = null

) {


}

