/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Information zu einem Kunden/zu einer Firma
 *
 * @param id Eindeutiger Key
 * @param name Bezeichner des Kunden
 * @param deeplink URL, Link auf den Kunden innerhalb der ITscope Plattform
 */


data class Customer (

    /* Eindeutiger Key */
    @get:JsonProperty("id")
    val id: kotlin.Long? = null,

    /* Bezeichner des Kunden */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* URL, Link auf den Kunden innerhalb der ITscope Plattform */
    @get:JsonProperty("deeplink")
    val deeplink: kotlin.String? = null

) {


}

