/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import de.itscope.api.dto.ApiViewType
import de.itscope.api.dto.ExportTableProvider
import de.itscope.api.dto.TableProviderSettings

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param apiViewType 
 * @param settings 
 * @param tableProvider 
 */


data class DealExportProfile21 (

    @get:JsonProperty("apiViewType")
    val apiViewType: ApiViewType? = null,

    @get:JsonProperty("settings")
    val settings: TableProviderSettings? = null,

    @get:JsonProperty("tableProvider")
    val tableProvider: ExportTableProvider? = null

) {


}

