/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import de.itscope.api.dto.ExportProfile
import de.itscope.api.dto.ExportTableObject
import de.itscope.api.dto.InMemoryTableObjectObject

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param exportProfile 
 * @param tables 
 * @param tableDefinitions 
 */


data class ExportTableProvider (

    @get:JsonProperty("exportProfile")
    val exportProfile: ExportProfile? = null,

    @get:JsonProperty("tables")
    val tables: kotlin.collections.List<InMemoryTableObjectObject>? = null,

    @get:JsonProperty("tableDefinitions")
    val tableDefinitions: kotlin.collections.Map<kotlin.String, ExportTableObject>? = null

) {


}

