/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import de.itscope.api.dto.RowDefinitionObject
import de.itscope.api.dto.RowTransformerObject
import de.itscope.api.dto.TableID

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param tableIdAsString 
 * @param rowDefinition 
 * @param rowTransformer 
 * @param tableIdFromClass 
 * @param tableId 
 */


data class ExportTableObject (

    @get:JsonProperty("tableIdAsString")
    val tableIdAsString: kotlin.String? = null,

    @get:JsonProperty("rowDefinition")
    val rowDefinition: RowDefinitionObject? = null,

    @get:JsonProperty("rowTransformer")
    val rowTransformer: RowTransformerObject? = null,

    @get:JsonProperty("tableIdFromClass")
    val tableIdFromClass: TableID? = null,

    @get:JsonProperty("tableId")
    val tableId: TableID? = null

) {


}

