/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param mandatory 
 * @param reference 
 * @param exportModelClass 
 * @param targetExportField 
 * @param targetGenericType 
 */


data class IExportFieldObject (

    @get:JsonProperty("id")
    val id: kotlin.String? = null,

    @get:JsonProperty("mandatory")
    val mandatory: kotlin.Boolean? = null,

    @get:JsonProperty("reference")
    val reference: kotlin.Boolean? = null,

    @get:JsonProperty("exportModelClass")
    val exportModelClass: kotlin.String? = null,

    @get:JsonProperty("targetExportField")
    val targetExportField: IExportFieldObject? = null,

    @get:JsonProperty("targetGenericType")
    val targetGenericType: kotlin.String? = null

) {


}

