/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param tableDefinition 
 * @param tableStreamWriter 
 */


data class InMemoryTableObjectObject (

    @get:JsonProperty("tableDefinition")
    val tableDefinition: kotlin.Any? = null,

    @get:JsonProperty("tableStreamWriter")
    val tableStreamWriter: kotlin.Any? = null

) {


}

