/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Details zur Liste der <a href=\"https://guide.itscope.com/kb/bestell-und-angebotsdaten-im-opentrans-2-1-format/\">OpenTrans 2.1 INVOICE</a> Dokumente
 *
 * @param transactionId ITscope TransaktionsId
 * @param lastUpdate Datum des letzten Updates des Dokuments
 * @param documentUrl <a href=\"https://guide.itscope.com/kb/business-documents-methode/\">API Business Dokumente Url</a> für den Download des Dokuments. Ist keine Url vorhanden hat diese Transaktion kein INVOICE Dokument, z.B. weil die Transaktion von Hand über das <a href=\"https://guide.itscope.com/kbtopic/verkaufsboard/\">Verkaufsboard</a> betätigt wurde.
 */


data class Invoice (

    /* ITscope TransaktionsId */
    @get:JsonProperty("transactionId")
    val transactionId: kotlin.String? = null,

    /* Datum des letzten Updates des Dokuments */
    @get:JsonProperty("lastUpdate")
    val lastUpdate: java.time.OffsetDateTime? = null,

    /* <a href=\"https://guide.itscope.com/kb/business-documents-methode/\">API Business Dokumente Url</a> für den Download des Dokuments. Ist keine Url vorhanden hat diese Transaktion kein INVOICE Dokument, z.B. weil die Transaktion von Hand über das <a href=\"https://guide.itscope.com/kbtopic/verkaufsboard/\">Verkaufsboard</a> betätigt wurde. */
    @get:JsonProperty("documentUrl")
    val documentUrl: kotlin.String? = null

) {


}

