/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import de.itscope.api.dto.ContentCategory
import de.itscope.api.dto.ContentModel
import de.itscope.api.dto.ContentProvider

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Contentdaten zu einem Produkt, die in Form von Schlüsseln vorliegen (z.B. Kategorie-IDs, Zolltarifnummern)
 *
 * @param key Key des Datensatzes, nicht eindeutig
 * @param langId Interne <a href=\"https://guide.itscope.com/kb/sprach-ids-fuer-content/\">Kennung der Sprache</a>, in der dieser Content vorliegt
 * @param contentModel 
 * @param contentProvider 
 * @param contentCategory 
 * @param `value` Inhalt des Content (Wert des Keys)
 * @param lang Sprachcode in ISO639, in der dieser Content vorliegt
 */


data class KeyContent (

    /* Key des Datensatzes, nicht eindeutig */
    @get:JsonProperty("key")
    val key: kotlin.Long? = null,

    /* Interne <a href=\"https://guide.itscope.com/kb/sprach-ids-fuer-content/\">Kennung der Sprache</a>, in der dieser Content vorliegt */
    @get:JsonProperty("langId")
    val langId: kotlin.Long? = null,

    @get:JsonProperty("contentModel")
    val contentModel: ContentModel? = null,

    @get:JsonProperty("contentProvider")
    val contentProvider: ContentProvider? = null,

    @get:JsonProperty("contentCategory")
    val contentCategory: ContentCategory? = null,

    /* Inhalt des Content (Wert des Keys) */
    @get:JsonProperty("value")
    val `value`: kotlin.String? = null,

    /* Sprachcode in ISO639, in der dieser Content vorliegt */
    @get:JsonProperty("lang")
    val lang: kotlin.String? = null

) {


}

