/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param addressType 
 * @param name 
 * @param name2 
 * @param name3 
 * @param street 
 * @param postOfficeBox 
 * @param zipCode 
 * @param city 
 * @param countryCoded 
 * @param clientNumber 
 * @param contactFirstName 
 * @param contactLastName 
 * @param contactEmail 
 * @param phone 
 */


data class LineItemAddress (

    @get:JsonProperty("addressType")
    val addressType: LineItemAddress.AddressType,

    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    @get:JsonProperty("name2")
    val name2: kotlin.String? = null,

    @get:JsonProperty("name3")
    val name3: kotlin.String? = null,

    @get:JsonProperty("street")
    val street: kotlin.String? = null,

    @get:JsonProperty("postOfficeBox")
    val postOfficeBox: kotlin.String? = null,

    @get:JsonProperty("zipCode")
    val zipCode: kotlin.String? = null,

    @get:JsonProperty("city")
    val city: kotlin.String? = null,

    @get:JsonProperty("countryCoded")
    val countryCoded: kotlin.String? = null,

    @get:JsonProperty("clientNumber")
    val clientNumber: kotlin.String? = null,

    @get:JsonProperty("contactFirstName")
    val contactFirstName: kotlin.String? = null,

    @get:JsonProperty("contactLastName")
    val contactLastName: kotlin.String? = null,

    @get:JsonProperty("contactEmail")
    val contactEmail: kotlin.String? = null,

    @get:JsonProperty("phone")
    val phone: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: invoice_recipient,delivery,customer
     */
    enum class AddressType(val value: kotlin.String) {
        @JsonProperty(value = "invoice_recipient") invoice_recipient("invoice_recipient"),
        @JsonProperty(value = "delivery") delivery("delivery"),
        @JsonProperty(value = "customer") customer("customer");
    }

}

