/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Hersteller eines Produkts.
 *
 * @param id Eindeutiger Key
 * @param name Bezeichner des Herstellers
 * @param shortName Kurzname des Herstellers
 * @param deeplink URL, Link auf den Hersteller innerhalb der ITscope Plattform
 */


data class Manufacturer (

    /* Eindeutiger Key */
    @get:JsonProperty("id")
    val id: kotlin.Long,

    /* Bezeichner des Herstellers */
    @get:JsonProperty("name")
    val name: kotlin.String,

    /* Kurzname des Herstellers */
    @get:JsonProperty("shortName")
    val shortName: kotlin.String,

    /* URL, Link auf den Hersteller innerhalb der ITscope Plattform */
    @get:JsonProperty("deeplink")
    val deeplink: kotlin.String

) {


}

