/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Details zu Bezahlinformationen
 *
 * @param transactionId TransaktionsId des Zahlungsdienstleisters
 * @param lastUpdate Letztes Update
 */


data class Payment (

    /* TransaktionsId des Zahlungsdienstleisters */
    @get:JsonProperty("transactionId")
    val transactionId: kotlin.String? = null,

    /* Letztes Update */
    @get:JsonProperty("lastUpdate")
    val lastUpdate: java.time.OffsetDateTime? = null

) {


}

