/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import de.itscope.api.dto.Product
import de.itscope.api.dto.ProductLogEntry

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param product 
 * @param log 
 */


data class ProductResponse (

    @get:JsonProperty("product")
    val product: kotlin.collections.List<Product>? = null,

    @get:JsonProperty("log")
    val log: kotlin.collections.List<ProductLogEntry>? = null

) {


}

