/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import de.itscope.api.dto.Accessory
import de.itscope.api.dto.Attribute
import de.itscope.api.dto.AttributeCluster
import de.itscope.api.dto.HistoricalDataItem
import de.itscope.api.dto.KeyContent
import de.itscope.api.dto.SupplierItem
import de.itscope.api.dto.SupplierPackagingInfo

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSetter
import com.fasterxml.jackson.annotation.Nulls

/**
 * Produkt des ITscope-Katalogs.
 *
 * @param puid Eindeutiger Key
 * @param manufacturerId Referenz auf den Hersteller dieses Produktes (n:1 auf Manufacturer.id)
 * @param productName Konfigurierbarer Produktbezeichner
 * @param productTypeId Referenz auf den Produkttyp dieses Produktes
 * @param productTypeGroupId Referenz auf Produkttyp-Gruppe (ProductTypeGroup.id, n:1)
 * @param productTypeGroupName Name der Gruppe von Produkttypen, z.B. Netzwerktechnik. Kann als 1. <a href=\"https://guide.itscope.com/kb/produktkategorien/\">Kategorieebene</a> verwendet werden.
 * @param productTypeName Bezeichner des Produkttyps. Kann als 2. <a href=\"https://guide.itscope.com/kb/produktkategorien/\">Kategorieebene</a> verwendet werden.
 * @param deeplink Deeplink auf die ITscope.com Plattform
 * @param standardHtmlDatasheet URL, Link auf HTML Standard-Datenblatt
 * @param entryDate Ab wann ist das Produkt auf der Plattform
 * @param aggregatedStatus Bester Verfügbarkeitsstatus
 * @param aggregatedStatusText Bester Verfügbarkeitsstatus
 * @param aggregatedStock Summe aller Lagerbestände
 * @param aggregatedSupplierItems Summe aller Distributoren zu diesem Produkt
 * @param supplierItem
 * @param ean EAN
 * @param manufacturerSKU Herstellerartikelnummer
 * @param icecatId IceCat ID
 * @param cnetId 1WorldSync ID
 * @param bechlemId Bechlem ID
 * @param eClass eClass ID
 * @param eClassV7 eClass Version 7
 * @param customsTariffNumber Zolltarifnummer
 * @param UNSPSC UNSPSC Classification Code
 * @param manufacturerName Name des Herstellers
 * @param shortDescription Konfigurierbare Kurzbezeichnung
 * @param longDescription <a href=\"https://guide.itscope.com/kb/produktbezeichner-und-produkttexte/\">Langtext</a> des Produktes
 * @param attributeTypeId1 Eindeutiger Attribut Key, um eine mögliche Unterkategorie aufzubauen, verweist 1:n auf AttributeCluster.attributeTypeId
 * @param attributeTypeName1 Bezeichner des Attributes, um eine mögliche Unterkategorie aufzubauen
 * @param attributeTypeId2 Eindeutiger Attribut Key, um eine mögliche Unterkategorie aufzubauen, verweist 1:n auf AttributeCluster.attributeTypeId
 * @param attributeTypeName2 Bezeichner des Attributes, um eine mögliche Unterkategorie aufzubauen
 * @param attributeTypeId3 Eindeutiger Attribut Key, um eine mögliche Unterkategorie aufzubauen, verweist 1:n auf AttributeCluster.attributeTypeId
 * @param attributeTypeName3 Bezeichner des Attributes, um eine mögliche Unterkategorie aufzubauen
 * @param attributeTypeId4 Eindeutiger Attribut Key, um eine mögliche Unterkategorie aufzubauen, verweist 1:n auf AttributeCluster.attributeTypeId
 * @param attributeTypeName4 Bezeichner des Attributes, um eine mögliche Unterkategorie aufzubauen
 * @param attributeTypeId5 Eindeutiger Attribut Key, um eine mögliche Unterkategorie aufzubauen, verweist 1:n auf AttributeCluster.attributeTypeId
 * @param attributeTypeName5 Bezeichner des Attributes, um eine mögliche Unterkategorie aufzubauen
 * @param attributeValue1 Eigenschaftswert für das Attribut aus ProductType.attributeTypeId1. Kann, falls vorhanden, als 3. <a href=\"https://guide.itscope.com/kb/produktkategorien/\">Kategorieebene</a> verwendet werden.
 * @param attributeValue2 Eigenschaftswert für das Attribut aus ProductType.attributeTypeId2. Kann, falls vorhanden, als 4. <a href=\"https://guide.itscope.com/kb/produktkategorien/\">Kategorieebene</a> verwendet werden.
 * @param attributeValue3 Eigenschaftswert für das Attribut aus ProductType.attributeTypeId3. Kann, falls vorhanden, als 5. <a href=\"https://guide.itscope.com/kb/produktkategorien/\">Kategorieebene</a> verwendet werden.
 * @param attributeValue4 Eigenschaftswert für das Attribut aus ProductType.attributeTypeId4
 * @param attributeValue5 Eigenschaftswert für das Attribut aus ProductType.attributeTypeId5
 * @param productSubTypeId ID der Bauart-Eigenschaft
 * @param productSubType Bauart-Eigenschaft des Produktes, z.B. Maus oder Tastatur für Eingabegeräte. Sollte <b>nicht</b> als 3. <a href=\"https://guide.itscope.com/kb/produktkategorien/\">Kategorieebene</a> verwendet werden.
 * @param productLineId ID der Produktlinie
 * @param productLine Produktlinie
 * @param productModel Produktmodellbezeichner
 * @param colorFamilyId ID der Farbfamilie
 * @param colorFamily Farbfamilie
 * @param estimateGrossWeight Gewicht in Kilogramm
 * @param grossDimX Länge des Produkts inklusive Maßeinheit
 * @param grossDimY Höhe des Produks inklusive Maßeinheit
 * @param grossDimZ Breite des Produkts inklusive Maßeinheit
 * @param combinedLengthAndGirth Gurtmaß
 * @param netWeight Nettogewicht
 * @param netDimX Nettomaß X
 * @param netDimY Nettomaß Y
 * @param netDimZ Nettomaß Z
 * @param valueAddedTaxGermany Deutscher Umsatzsteuersatz
 * @param standardPdfDatasheet URL, Link auf PDF Standard-Datenblatt
 * @param manufacturerSite URL, Link auf Herstellerseite
 * @param manufacturerDatasheet URL, Link auf Herstellerdatenblatt
 * @param imageThumb Vorschau des besten <a href=\"https://guide.itscope.com/kb/produktbilder/\">Produktbildes</a>
 * @param imageThumbWidth Breite des Bild Mediums in Pixel
 * @param imageThumbHeight Höhe des Bild Mediums in Pixel
 * @param imageHighRes1 Link auf ein hochaufgelöstes Produktbild?
 * @param imageWidth1 Breite des Bild Mediums in Pixel
 * @param imageHeight1 Höhe des Bild Mediums in Pixel
 * @param image2 Link auf ein weiteres gutes <a href=\"https://guide.itscope.com/kb/produktbilder/\">Produktbild</a>, bevorzugt das einer Produktverpackung (nie das gleiche wie das erste Bild)
 * @param imageWidth2 Breite des Bild Mediums in Pixel
 * @param imageHeight2 Höhe des Bild Mediums in Pixel
 * @param image3 Link auf erstes <a href=\"https://guide.itscope.com/kb/produktbilder/\">Bild</a> in der Galerie (niemals eines der bereits aufgeführten)
 * @param imageWidth3 Breite des Bild Mediums in Pixel
 * @param imageHeight3 Höhe des Bild Mediums in Pixel
 * @param image4 Link auf zweites <a href=\"https://guide.itscope.com/kb/produktbilder/\">Bild</a> in der Galerie (niemals eines der bereits aufgeführten)
 * @param imageWidth4 Breite des Bild Mediums in Pixel
 * @param imageHeight4 Höhe des Bild Mediums in Pixel
 * @param image5 Link auf drittes <a href=\"https://guide.itscope.com/kb/produktbilder/\">Bild</a> in der Galerie (niemals eines der bereits aufgeführten)
 * @param imageWidth5 Breite des Bild Mediums in Pixel
 * @param imageHeight5 Höhe des Bild Mediums in Pixel
 * @param energyLabel Link auf das Energielabel <a href=\"https://guide.itscope.com/kb/produktbilder/\">Bild</a>
 * @param energyEfficiencyClass Energieeffizienzklasse
 * @param rank Allgemeiner Beliebtheitsrang (Rang 1 bis n, eine hohe Zahl entspricht einem schlechten Ranking)
 * @param qualification <a href=\"https://guide.itscope.com/kb/qualifizierung-des-produktes/\">Qualifizierung des Produkts</a>
 * @param warrantyText <a href=\"https://guide.itscope.com/kb/produktbezeichner-und-produkttexte/\">Garantietext</a> des Produktes
 * @param marketingText <a href=\"https://guide.itscope.com/kb/produktbezeichner-und-produkttexte/\">Marketingtext</a> für das Produkt
 * @param keySellingPoints Key Selling Points
 * @param packageContents Lieferumfang
 * @param productFeatures Produktfeatures
 * @param htmlMainSpecs <a href=\"https://guide.itscope.com/kb/technische-eigenschaften-im-html-format-htmlspecs/\">Technische Eigenschaften</a> des Produktes in Kurzform, getrennt mit br-Tags
 * @param htmlSpecs <a href=\"https://guide.itscope.com/kb/technische-eigenschaften-im-html-format-htmlspecs/\">Technische Eigenschaften</a> des Produktes, im HTML Format
 * @param recommendedRetailPriceNet UVP des Herstellers
 * @param price Preisbasis für den <a href=\"https://guide.itscope.com/kb/herkunft-der-preis-und-bestandsinformation/\">kalkulierten Preis</a>
 * @param priceCalc Kalkulierter Preis, auf Grundlage der individuellen <a href=\"https://guide.itscope.com/kbtopic/preiskalkulation/\">Preiskalkulation</a>
 * @param currencyCode Währungseinheit, die für diese Preisinformation gilt
 * @param priceCalcVat Umsatzsteuersatz, der zur Berechnung des <a href=\"https://guide.itscope.com/kb/herkunft-der-preis-und-bestandsinformation/\">kalkulierten Preises</a> benutzt wurde
 * @param priceLastUpdate Zeitpunkt der letzten Aktualisierung der Preisinformation
 * @param priceSupplierId Referenz auf einen Lieferanten (1:1), der die Bezugsquelle mit dieser Preisinformation bereitgestellt hat
 * @param priceSupplierName Name des Lieferanten, der diese Bezugsquelle bereitgestellt hat
 * @param priceSupplierItemId Referenz auf eine Bezugsquelle (n:1); wenn dieses Feld null ist, dann bezieht sich die Preisinformation auf ein Produkt (Bezugsquellenreferenz und Produktreferenz schließen sich gegenseitig aus)
 * @param priceSupplierSKU Produktbezeichner des Lieferanten, der diese Bezugsquelle bereitgestellt hat
 * @param stockSupplierText Textuelle Bestandsinformation des Lieferanten, direkt übernommen, ohne Interpretation
 * @param stockStatus Numerischer Schlüssel des <a href=\"https://guide.itscope.com/kb/verfuegbarkeitsstatus/\">Lieferstatus dieser Bestandsinformation</a>
 * @param stockStatusText <a href=\"https://guide.itscope.com/kb/verfuegbarkeitsstatus/\">Lieferstatus dieser Bestandsinformation</a>, z.B. \"auf Lager\" oder \"im Außenlager\"
 * @param stock Bestandsmenge des in dieser Struktur angegebenen Lieferstatus
 * @param externalStock Im Außenlager befindliche Bestandsmenge (Zusatzinformation einiger Lieferanten in Strukturen des Lieferstatus \"auf Lager\")
 * @param incomingStock Im Zulauf befindliche Bestandsmenge  (Zusatzinformation einiger Lieferanten in Strukturen des Lieferstatus \"auf Lager\")
 * @param stockAvailabilityDate Liefertermin für nicht auf Lager befindliche Ware
 * @param stockLastUpdate Zeitpunkt der letzten Aktualisierung der Bestandsinformation
 * @param contractTypeId Der <a href=\"https://guide.itscope.com/kb/produktart/\">Vertragstyp</a> bei Lizenz- und Serviceprodukten
 * @param contractTypeName Der Name des <a href=\"https://guide.itscope.com/kb/produktart/\">Vertragstyps</a> bei Lizenz- und Serviceprodukten
 * @param priceBillingPeriod Beschreibt die Länge des Zyklus des Abrechnungszeitraums
 * @param priceBillingPeriodUnit Beschreibt die Zeiteinheit des Abrechnungszeitraums (z.B. \"Years\", \"Months\")
 * @param priceSubscriptionPeriod Beschreibt die Länge der Vertragsdauer
 * @param priceSubscriptionPeriodUnit Beschreibt die Zeiteinheit der Vertragsdauer (z.B. \"Years\", \"Months\")
 * @param attribute
 * @param attributeCluster
 * @param accessory
 * @param historicalDataItem
 * @param supplierPackagingInfo
 * @param keyContent
 */


data class Product(

    /* Eindeutiger Key */
    @get:JsonProperty("puid")
    val puid: kotlin.Long,

    /* Referenz auf den Hersteller dieses Produktes (n:1 auf Manufacturer.id) */
    @get:JsonProperty("manufacturerId")
    val manufacturerId: kotlin.Long,

    /* Konfigurierbarer Produktbezeichner */
    @get:JsonProperty("productName")
    val productName: kotlin.String,

    /* Referenz auf den Produkttyp dieses Produktes */
    @get:JsonProperty("productTypeId")
    val productTypeId: kotlin.Long,

    /* Referenz auf Produkttyp-Gruppe (ProductTypeGroup.id, n:1) */
    @get:JsonProperty("productTypeGroupId")
    val productTypeGroupId: kotlin.String,

    /* Name der Gruppe von Produkttypen, z.B. Netzwerktechnik. Kann als 1. <a href=\"https://guide.itscope.com/kb/produktkategorien/\">Kategorieebene</a> verwendet werden. */
    @get:JsonProperty("productTypeGroupName")
    val productTypeGroupName: kotlin.String,

    /* Bezeichner des Produkttyps. Kann als 2. <a href=\"https://guide.itscope.com/kb/produktkategorien/\">Kategorieebene</a> verwendet werden. */
    @get:JsonProperty("productTypeName")
    val productTypeName: kotlin.String,

    /* Deeplink auf die ITscope.com Plattform */
    @get:JsonProperty("deeplink")
    val deeplink: kotlin.String,

    /* URL, Link auf HTML Standard-Datenblatt */
    @get:JsonProperty("standardHtmlDatasheet")
    val standardHtmlDatasheet: kotlin.String,

    /* Ab wann ist das Produkt auf der Plattform */
    @get:JsonProperty("entryDate")
    val entryDate: java.time.OffsetDateTime,

    /* Bester Verfügbarkeitsstatus */
    @get:JsonProperty("aggregatedStatus")
    val aggregatedStatus: kotlin.Int,

    /* Bester Verfügbarkeitsstatus */
    @get:JsonProperty("aggregatedStatusText")
    val aggregatedStatusText: kotlin.String,

    /* Summe aller Lagerbestände */
    @get:JsonProperty("aggregatedStock")
    val aggregatedStock: kotlin.Int,

    /* Summe aller Distributoren zu diesem Produkt */
    @get:JsonProperty("aggregatedSupplierItems")
    val aggregatedSupplierItems: kotlin.Int,

    @get:JsonProperty("supplierItem")
    @set:JsonSetter(nulls = Nulls.AS_EMPTY)
    var supplierItem: List<SupplierItem> = emptyList(),

    /* EAN */
    @get:JsonProperty("ean")
    val ean: kotlin.String? = null,

    /* Herstellerartikelnummer */
    @get:JsonProperty("manufacturerSKU")
    val manufacturerSKU: kotlin.String? = null,

    /* IceCat ID */
    @get:JsonProperty("icecatId")
    val icecatId: kotlin.String? = null,

    /* 1WorldSync ID */
    @get:JsonProperty("cnetId")
    val cnetId: kotlin.String? = null,

    /* Bechlem ID */
    @get:JsonProperty("bechlemId")
    val bechlemId: kotlin.String? = null,

    /* eClass ID */
    @get:JsonProperty("eClass")
    val eClass: kotlin.String? = null,

    /* eClass Version 7 */
    @get:JsonProperty("eClassV7")
    val eClassV7: kotlin.String? = null,

    /* Zolltarifnummer */
    @get:JsonProperty("customsTariffNumber")
    val customsTariffNumber: kotlin.String? = null,

    /* UNSPSC Classification Code */
    @get:JsonProperty("UNSPSC")
    val UNSPSC: kotlin.String? = null,

    /* Name des Herstellers */
    @get:JsonProperty("manufacturerName")
    val manufacturerName: kotlin.String? = null,

    /* Konfigurierbare Kurzbezeichnung */
    @get:JsonProperty("shortDescription")
    val shortDescription: kotlin.String? = null,

    /* <a href=\"https://guide.itscope.com/kb/produktbezeichner-und-produkttexte/\">Langtext</a> des Produktes */
    @get:JsonProperty("longDescription")
    val longDescription: kotlin.String? = null,

    /* Eindeutiger Attribut Key, um eine mögliche Unterkategorie aufzubauen, verweist 1:n auf AttributeCluster.attributeTypeId */
    @get:JsonProperty("attributeTypeId1")
    val attributeTypeId1: kotlin.Long? = null,

    /* Bezeichner des Attributes, um eine mögliche Unterkategorie aufzubauen */
    @get:JsonProperty("attributeTypeName1")
    val attributeTypeName1: kotlin.String? = null,

    /* Eindeutiger Attribut Key, um eine mögliche Unterkategorie aufzubauen, verweist 1:n auf AttributeCluster.attributeTypeId */
    @get:JsonProperty("attributeTypeId2")
    val attributeTypeId2: kotlin.Long? = null,

    /* Bezeichner des Attributes, um eine mögliche Unterkategorie aufzubauen */
    @get:JsonProperty("attributeTypeName2")
    val attributeTypeName2: kotlin.String? = null,

    /* Eindeutiger Attribut Key, um eine mögliche Unterkategorie aufzubauen, verweist 1:n auf AttributeCluster.attributeTypeId */
    @get:JsonProperty("attributeTypeId3")
    val attributeTypeId3: kotlin.Long? = null,

    /* Bezeichner des Attributes, um eine mögliche Unterkategorie aufzubauen */
    @get:JsonProperty("attributeTypeName3")
    val attributeTypeName3: kotlin.String? = null,

    /* Eindeutiger Attribut Key, um eine mögliche Unterkategorie aufzubauen, verweist 1:n auf AttributeCluster.attributeTypeId */
    @get:JsonProperty("attributeTypeId4")
    val attributeTypeId4: kotlin.Long? = null,

    /* Bezeichner des Attributes, um eine mögliche Unterkategorie aufzubauen */
    @get:JsonProperty("attributeTypeName4")
    val attributeTypeName4: kotlin.String? = null,

    /* Eindeutiger Attribut Key, um eine mögliche Unterkategorie aufzubauen, verweist 1:n auf AttributeCluster.attributeTypeId */
    @get:JsonProperty("attributeTypeId5")
    val attributeTypeId5: kotlin.Long? = null,

    /* Bezeichner des Attributes, um eine mögliche Unterkategorie aufzubauen */
    @get:JsonProperty("attributeTypeName5")
    val attributeTypeName5: kotlin.String? = null,

    /* Eigenschaftswert für das Attribut aus ProductType.attributeTypeId1. Kann, falls vorhanden, als 3. <a href=\"https://guide.itscope.com/kb/produktkategorien/\">Kategorieebene</a> verwendet werden. */
    @get:JsonProperty("attributeValue1")
    val attributeValue1: kotlin.String? = null,

    /* Eigenschaftswert für das Attribut aus ProductType.attributeTypeId2. Kann, falls vorhanden, als 4. <a href=\"https://guide.itscope.com/kb/produktkategorien/\">Kategorieebene</a> verwendet werden. */
    @get:JsonProperty("attributeValue2")
    val attributeValue2: kotlin.String? = null,

    /* Eigenschaftswert für das Attribut aus ProductType.attributeTypeId3. Kann, falls vorhanden, als 5. <a href=\"https://guide.itscope.com/kb/produktkategorien/\">Kategorieebene</a> verwendet werden. */
    @get:JsonProperty("attributeValue3")
    val attributeValue3: kotlin.String? = null,

    /* Eigenschaftswert für das Attribut aus ProductType.attributeTypeId4 */
    @get:JsonProperty("attributeValue4")
    val attributeValue4: kotlin.String? = null,

    /* Eigenschaftswert für das Attribut aus ProductType.attributeTypeId5 */
    @get:JsonProperty("attributeValue5")
    val attributeValue5: kotlin.String? = null,

    /* ID der Bauart-Eigenschaft */
    @get:JsonProperty("productSubTypeId")
    val productSubTypeId: kotlin.String? = null,

    /* Bauart-Eigenschaft des Produktes, z.B. Maus oder Tastatur für Eingabegeräte. Sollte <b>nicht</b> als 3. <a href=\"https://guide.itscope.com/kb/produktkategorien/\">Kategorieebene</a> verwendet werden. */
    @get:JsonProperty("productSubType")
    val productSubType: kotlin.String? = null,

    /* ID der Produktlinie */
    @get:JsonProperty("productLineId")
    val productLineId: kotlin.Long? = null,

    /* Produktlinie */
    @get:JsonProperty("productLine")
    val productLine: kotlin.String? = null,

    /* Produktmodellbezeichner */
    @get:JsonProperty("productModel")
    val productModel: kotlin.String? = null,

    /* ID der Farbfamilie */
    @get:JsonProperty("colorFamilyId")
    val colorFamilyId: kotlin.String? = null,

    /* Farbfamilie */
    @get:JsonProperty("colorFamily")
    val colorFamily: kotlin.String? = null,

    /* Gewicht in Kilogramm */
    @get:JsonProperty("estimateGrossWeight")
    val estimateGrossWeight: kotlin.Double? = null,

    /* Länge des Produkts inklusive Maßeinheit */
    @get:JsonProperty("grossDimX")
    val grossDimX: kotlin.String? = null,

    /* Höhe des Produks inklusive Maßeinheit */
    @get:JsonProperty("grossDimY")
    val grossDimY: kotlin.String? = null,

    /* Breite des Produkts inklusive Maßeinheit */
    @get:JsonProperty("grossDimZ")
    val grossDimZ: kotlin.String? = null,

    /* Gurtmaß */
    @get:JsonProperty("combinedLengthAndGirth")
    val combinedLengthAndGirth: kotlin.String? = null,

    /* Nettogewicht */
    @get:JsonProperty("netWeight")
    val netWeight: kotlin.String? = null,

    /* Nettomaß X */
    @get:JsonProperty("netDimX")
    val netDimX: kotlin.String? = null,

    /* Nettomaß Y */
    @get:JsonProperty("netDimY")
    val netDimY: kotlin.String? = null,

    /* Nettomaß Z */
    @get:JsonProperty("netDimZ")
    val netDimZ: kotlin.String? = null,

    /* Deutscher Umsatzsteuersatz */
    @get:JsonProperty("valueAddedTaxGermany")
    val valueAddedTaxGermany: kotlin.Int? = null,

    /* URL, Link auf PDF Standard-Datenblatt */
    @get:JsonProperty("standardPdfDatasheet")
    val standardPdfDatasheet: kotlin.String? = null,

    /* URL, Link auf Herstellerseite */
    @get:JsonProperty("manufacturerSite")
    val manufacturerSite: kotlin.String? = null,

    /* URL, Link auf Herstellerdatenblatt */
    @get:JsonProperty("manufacturerDatasheet")
    val manufacturerDatasheet: kotlin.String? = null,

    /* Vorschau des besten <a href=\"https://guide.itscope.com/kb/produktbilder/\">Produktbildes</a> */
    @get:JsonProperty("imageThumb")
    val imageThumb: kotlin.String? = null,

    /* Breite des Bild Mediums in Pixel */
    @get:JsonProperty("imageThumbWidth")
    val imageThumbWidth: kotlin.Int? = null,

    /* Höhe des Bild Mediums in Pixel */
    @get:JsonProperty("imageThumbHeight")
    val imageThumbHeight: kotlin.Int? = null,

    /* Link auf ein hochaufgelöstes Produktbild? */
    @get:JsonProperty("imageHighRes1")
    val imageHighRes1: kotlin.String? = null,

    /* Breite des Bild Mediums in Pixel */
    @get:JsonProperty("imageWidth1")
    val imageWidth1: kotlin.Int? = null,

    /* Höhe des Bild Mediums in Pixel */
    @get:JsonProperty("imageHeight1")
    val imageHeight1: kotlin.Int? = null,

    /* Link auf ein weiteres gutes <a href=\"https://guide.itscope.com/kb/produktbilder/\">Produktbild</a>, bevorzugt das einer Produktverpackung (nie das gleiche wie das erste Bild) */
    @get:JsonProperty("image2")
    val image2: kotlin.String? = null,

    /* Breite des Bild Mediums in Pixel */
    @get:JsonProperty("imageWidth2")
    val imageWidth2: kotlin.Int? = null,

    /* Höhe des Bild Mediums in Pixel */
    @get:JsonProperty("imageHeight2")
    val imageHeight2: kotlin.Int? = null,

    /* Link auf erstes <a href=\"https://guide.itscope.com/kb/produktbilder/\">Bild</a> in der Galerie (niemals eines der bereits aufgeführten) */
    @get:JsonProperty("image3")
    val image3: kotlin.String? = null,

    /* Breite des Bild Mediums in Pixel */
    @get:JsonProperty("imageWidth3")
    val imageWidth3: kotlin.Int? = null,

    /* Höhe des Bild Mediums in Pixel */
    @get:JsonProperty("imageHeight3")
    val imageHeight3: kotlin.Int? = null,

    /* Link auf zweites <a href=\"https://guide.itscope.com/kb/produktbilder/\">Bild</a> in der Galerie (niemals eines der bereits aufgeführten) */
    @get:JsonProperty("image4")
    val image4: kotlin.String? = null,

    /* Breite des Bild Mediums in Pixel */
    @get:JsonProperty("imageWidth4")
    val imageWidth4: kotlin.Int? = null,

    /* Höhe des Bild Mediums in Pixel */
    @get:JsonProperty("imageHeight4")
    val imageHeight4: kotlin.Int? = null,

    /* Link auf drittes <a href=\"https://guide.itscope.com/kb/produktbilder/\">Bild</a> in der Galerie (niemals eines der bereits aufgeführten) */
    @get:JsonProperty("image5")
    val image5: kotlin.String? = null,

    /* Breite des Bild Mediums in Pixel */
    @get:JsonProperty("imageWidth5")
    val imageWidth5: kotlin.Int? = null,

    /* Höhe des Bild Mediums in Pixel */
    @get:JsonProperty("imageHeight5")
    val imageHeight5: kotlin.Int? = null,

    /* Link auf das Energielabel <a href=\"https://guide.itscope.com/kb/produktbilder/\">Bild</a> */
    @get:JsonProperty("energyLabel")
    val energyLabel: kotlin.String? = null,

    /* Energieeffizienzklasse */
    @get:JsonProperty("energyEfficiencyClass")
    val energyEfficiencyClass: kotlin.String? = null,

    /* Allgemeiner Beliebtheitsrang (Rang 1 bis n, eine hohe Zahl entspricht einem schlechten Ranking) */
    @get:JsonProperty("rank")
    val rank: kotlin.Int? = null,

    /* <a href=\"https://guide.itscope.com/kb/qualifizierung-des-produktes/\">Qualifizierung des Produkts</a> */
    @get:JsonProperty("qualification")
    val qualification: kotlin.Int? = null,

    /* <a href=\"https://guide.itscope.com/kb/produktbezeichner-und-produkttexte/\">Garantietext</a> des Produktes */
    @get:JsonProperty("warrantyText")
    val warrantyText: kotlin.String? = null,

    /* <a href=\"https://guide.itscope.com/kb/produktbezeichner-und-produkttexte/\">Marketingtext</a> für das Produkt */
    @get:JsonProperty("marketingText")
    val marketingText: kotlin.String? = null,

    /* Key Selling Points */
    @get:JsonProperty("keySellingPoints")
    val keySellingPoints: kotlin.String? = null,

    /* Lieferumfang */
    @get:JsonProperty("packageContents")
    val packageContents: kotlin.String? = null,

    /* Produktfeatures */
    @get:JsonProperty("productFeatures")
    val productFeatures: kotlin.String? = null,

    /* <a href=\"https://guide.itscope.com/kb/technische-eigenschaften-im-html-format-htmlspecs/\">Technische Eigenschaften</a> des Produktes in Kurzform, getrennt mit br-Tags */
    @get:JsonProperty("htmlMainSpecs")
    val htmlMainSpecs: kotlin.String? = null,

    /* <a href=\"https://guide.itscope.com/kb/technische-eigenschaften-im-html-format-htmlspecs/\">Technische Eigenschaften</a> des Produktes, im HTML Format */
    @get:JsonProperty("htmlSpecs")
    val htmlSpecs: kotlin.String? = null,

    /* UVP des Herstellers */
    @get:JsonProperty("recommendedRetailPriceNet")
    val recommendedRetailPriceNet: kotlin.Double? = null,

    /* Preisbasis für den <a href=\"https://guide.itscope.com/kb/herkunft-der-preis-und-bestandsinformation/\">kalkulierten Preis</a> */
    @get:JsonProperty("price")
    val price: java.math.BigDecimal? = null,

    /* Kalkulierter Preis, auf Grundlage der individuellen <a href=\"https://guide.itscope.com/kbtopic/preiskalkulation/\">Preiskalkulation</a> */
    @get:JsonProperty("priceCalc")
    val priceCalc: java.math.BigDecimal? = null,

    /* Währungseinheit, die für diese Preisinformation gilt */
    @get:JsonProperty("currencyCode")
    val currencyCode: kotlin.String? = null,

    /* Umsatzsteuersatz, der zur Berechnung des <a href=\"https://guide.itscope.com/kb/herkunft-der-preis-und-bestandsinformation/\">kalkulierten Preises</a> benutzt wurde */
    @get:JsonProperty("priceCalcVat")
    val priceCalcVat: java.math.BigDecimal? = null,

    /* Zeitpunkt der letzten Aktualisierung der Preisinformation */
    @get:JsonProperty("priceLastUpdate")
    val priceLastUpdate: java.time.OffsetDateTime? = null,

    /* Referenz auf einen Lieferanten (1:1), der die Bezugsquelle mit dieser Preisinformation bereitgestellt hat */
    @get:JsonProperty("priceSupplierId")
    val priceSupplierId: kotlin.Long? = null,

    /* Name des Lieferanten, der diese Bezugsquelle bereitgestellt hat */
    @get:JsonProperty("priceSupplierName")
    val priceSupplierName: kotlin.String? = null,

    /* Referenz auf eine Bezugsquelle (n:1); wenn dieses Feld null ist, dann bezieht sich die Preisinformation auf ein Produkt (Bezugsquellenreferenz und Produktreferenz schließen sich gegenseitig aus) */
    @get:JsonProperty("priceSupplierItemId")
    val priceSupplierItemId: kotlin.Long? = null,

    /* Produktbezeichner des Lieferanten, der diese Bezugsquelle bereitgestellt hat */
    @get:JsonProperty("priceSupplierSKU")
    val priceSupplierSKU: kotlin.String? = null,

    /* Textuelle Bestandsinformation des Lieferanten, direkt übernommen, ohne Interpretation */
    @get:JsonProperty("stockSupplierText")
    val stockSupplierText: kotlin.String? = null,

    /* Numerischer Schlüssel des <a href=\"https://guide.itscope.com/kb/verfuegbarkeitsstatus/\">Lieferstatus dieser Bestandsinformation</a> */
    @get:JsonProperty("stockStatus")
    val stockStatus: kotlin.Int? = null,

    /* <a href=\"https://guide.itscope.com/kb/verfuegbarkeitsstatus/\">Lieferstatus dieser Bestandsinformation</a>, z.B. \"auf Lager\" oder \"im Außenlager\" */
    @get:JsonProperty("stockStatusText")
    val stockStatusText: kotlin.String? = null,

    /* Bestandsmenge des in dieser Struktur angegebenen Lieferstatus */
    @get:JsonProperty("stock")
    val stock: kotlin.Int? = null,

    /* Im Außenlager befindliche Bestandsmenge (Zusatzinformation einiger Lieferanten in Strukturen des Lieferstatus \"auf Lager\") */
    @get:JsonProperty("externalStock")
    val externalStock: kotlin.Int? = null,

    /* Im Zulauf befindliche Bestandsmenge  (Zusatzinformation einiger Lieferanten in Strukturen des Lieferstatus \"auf Lager\") */
    @get:JsonProperty("incomingStock")
    val incomingStock: kotlin.Int? = null,

    /* Liefertermin für nicht auf Lager befindliche Ware */
    @get:JsonProperty("stockAvailabilityDate")
    val stockAvailabilityDate: java.time.OffsetDateTime? = null,

    /* Zeitpunkt der letzten Aktualisierung der Bestandsinformation */
    @get:JsonProperty("stockLastUpdate")
    val stockLastUpdate: java.time.OffsetDateTime? = null,

    /* Der <a href=\"https://guide.itscope.com/kb/produktart/\">Vertragstyp</a> bei Lizenz- und Serviceprodukten */
    @get:JsonProperty("contractTypeId")
    val contractTypeId: kotlin.Int? = null,

    /* Der Name des <a href=\"https://guide.itscope.com/kb/produktart/\">Vertragstyps</a> bei Lizenz- und Serviceprodukten */
    @get:JsonProperty("contractTypeName")
    val contractTypeName: kotlin.String? = null,

    /* Beschreibt die Länge des Zyklus des Abrechnungszeitraums */
    @get:JsonProperty("priceBillingPeriod")
    val priceBillingPeriod: kotlin.Int? = null,

    /* Beschreibt die Zeiteinheit des Abrechnungszeitraums (z.B. \"Years\", \"Months\") */
    @get:JsonProperty("priceBillingPeriodUnit")
    val priceBillingPeriodUnit: kotlin.String? = null,

    /* Beschreibt die Länge der Vertragsdauer */
    @get:JsonProperty("priceSubscriptionPeriod")
    val priceSubscriptionPeriod: kotlin.Int? = null,

    /* Beschreibt die Zeiteinheit der Vertragsdauer (z.B. \"Years\", \"Months\") */
    @get:JsonProperty("priceSubscriptionPeriodUnit")
    val priceSubscriptionPeriodUnit: kotlin.String? = null,

    @get:JsonProperty("attribute")
    val attribute: List<Attribute>? = null,

    @get:JsonProperty("attributeCluster")
    val attributeCluster: List<AttributeCluster>? = null,

    @get:JsonProperty("accessory")
    val accessory: List<Accessory>? = null,

    @get:JsonProperty("historicalDataItem")
    val historicalDataItem: List<HistoricalDataItem>? = null,

    @get:JsonProperty("supplierPackagingInfo")
    val supplierPackagingInfo: SupplierPackagingInfo? = null,

    @get:JsonProperty("keyContent")
    val keyContent: List<KeyContent>? = null

) {

    val productNameShort: String
        get() = productName.substringBefore("- ")

    fun simpleString(): String {
        return "Product($puid, $manufacturerName, $productTypeName, $productNameShort, $price €)"
    }

}

