/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Produkttyp-Gruppierung.
 *
 * @param id Eindeutiger Key
 * @param name Name der Gruppe von Produkttypen, z.B. Netzwerktechnik. Kann als 1. <a href=\"https://guide.itscope.com/kb/produktkategorien/\">Kategorieebene</a> verwendet werden.
 */


data class ProductTypeGroup (

    /* Eindeutiger Key */
    @get:JsonProperty("id")
    val id: kotlin.String,

    /* Name der Gruppe von Produkttypen, z.B. Netzwerktechnik. Kann als 1. <a href=\"https://guide.itscope.com/kb/produktkategorien/\">Kategorieebene</a> verwendet werden. */
    @get:JsonProperty("name")
    val name: kotlin.String

) {


}

