/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param cause 
 */


data class ProductLogEntry (

    @get:JsonProperty("id")
    val id: kotlin.Long? = null,

    @get:JsonProperty("cause")
    val cause: kotlin.String? = null

) {


}

