/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Informationen, Preis und Verfügbarkeit eines Projektartikels
 *
 * @param manufacturerProjectId Projektnummer des Herstellers (eindeutiger Key)
 * @param price Projektpreis
 * @param remainingQuantity Verbleibendes Kontingent
 * @param supplierProjectId Projektnummer des Lieferanten
 * @param projectName Projektbezeichnung
 * @param endCustomer Endkunde des Projektartikels
 * @param validFrom Datum, ab dem die Projektkonditionen gelten
 * @param validTo Datum, ab dem die Projektkonditionen ungültig werden
 * @param targetQuantity Vereinbarte Menge im Projektrahmen
 * @param minQuantity Mindestbestellmenge für dieses Projekt
 * @param projectLastUpdate Zeitpunkt der letzten Aktualisierung der Projektinformationen
 */


data class Project (

    /* Projektnummer des Herstellers (eindeutiger Key) */
    @get:JsonProperty("manufacturerProjectId")
    val manufacturerProjectId: kotlin.String,

    /* Projektpreis */
    @get:JsonProperty("price")
    val price: java.math.BigDecimal,

    /* Verbleibendes Kontingent */
    @get:JsonProperty("remainingQuantity")
    val remainingQuantity: kotlin.Int,

    /* Projektnummer des Lieferanten */
    @get:JsonProperty("supplierProjectId")
    val supplierProjectId: kotlin.String? = null,

    /* Projektbezeichnung */
    @get:JsonProperty("projectName")
    val projectName: kotlin.String? = null,

    /* Endkunde des Projektartikels */
    @get:JsonProperty("endCustomer")
    val endCustomer: kotlin.String? = null,

    /* Datum, ab dem die Projektkonditionen gelten */
    @get:JsonProperty("validFrom")
    val validFrom: java.time.OffsetDateTime? = null,

    /* Datum, ab dem die Projektkonditionen ungültig werden */
    @get:JsonProperty("validTo")
    val validTo: java.time.OffsetDateTime? = null,

    /* Vereinbarte Menge im Projektrahmen */
    @get:JsonProperty("targetQuantity")
    val targetQuantity: kotlin.Int? = null,

    /* Mindestbestellmenge für dieses Projekt */
    @get:JsonProperty("minQuantity")
    val minQuantity: kotlin.Int? = null,

    /* Zeitpunkt der letzten Aktualisierung der Projektinformationen */
    @get:JsonProperty("projectLastUpdate")
    val projectLastUpdate: java.time.OffsetDateTime? = null

) {


}

