/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Detailinformationen zu einem Angebot
 *
 * @param quoteId Eindeutiger Key des Angebots (intern)
 * @param quoteNo Angebotsnummer, wie sie auf dem Dokument angezeigt wird
 * @param shortUrl Individueller Link auf das Angebot, für den Empfänger des Angebots
 * @param name Vom Ersteller des Angebots vergebener Name
 * @param status Zustand des Angebots, z.B. \"In Verhandlung\"
 * @param lastModified Letztes Änderungsdatum
 * @param validUntil Gültigkeitsdatum, bis zu welchem das Angebot gilt
 * @param organisation Name der Organisation, an die das Angebot gerichtet ist
 * @param person Name des Empfängers (Vor- und Nachname)
 * @param itemCount Anzahl der Positionen im Angebot (inklusive optionalen Positionen)
 * @param deeplink Deeplink zum Angebot
 * @param documentUrl <a href=\"https://guide.itscope.com/kb/business-documents-methode/\">API Business Dokumente Url</a> für den Download des Dokuments.
 * @param archived Archivflag des Angebots
 * @param customerNumber Kundennummer des Angebots
 * @param creator Ersteller des Angebots
 * @param totalPrice Gesamtbetrag des Angebots (brutto)
 */


data class Quote (

    /* Eindeutiger Key des Angebots (intern) */
    @get:JsonProperty("quoteId")
    val quoteId: kotlin.String? = null,

    /* Angebotsnummer, wie sie auf dem Dokument angezeigt wird */
    @get:JsonProperty("quoteNo")
    val quoteNo: kotlin.String? = null,

    /* Individueller Link auf das Angebot, für den Empfänger des Angebots */
    @get:JsonProperty("shortUrl")
    val shortUrl: kotlin.String? = null,

    /* Vom Ersteller des Angebots vergebener Name */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Zustand des Angebots, z.B. \"In Verhandlung\" */
    @get:JsonProperty("status")
    val status: kotlin.String? = null,

    /* Letztes Änderungsdatum */
    @get:JsonProperty("lastModified")
    val lastModified: java.time.OffsetDateTime? = null,

    /* Gültigkeitsdatum, bis zu welchem das Angebot gilt */
    @get:JsonProperty("validUntil")
    val validUntil: java.time.OffsetDateTime? = null,

    /* Name der Organisation, an die das Angebot gerichtet ist */
    @get:JsonProperty("organisation")
    val organisation: kotlin.String? = null,

    /* Name des Empfängers (Vor- und Nachname) */
    @get:JsonProperty("person")
    val person: kotlin.String? = null,

    /* Anzahl der Positionen im Angebot (inklusive optionalen Positionen) */
    @get:JsonProperty("itemCount")
    val itemCount: kotlin.Int? = null,

    /* Deeplink zum Angebot */
    @get:JsonProperty("deeplink")
    val deeplink: kotlin.String? = null,

    /* <a href=\"https://guide.itscope.com/kb/business-documents-methode/\">API Business Dokumente Url</a> für den Download des Dokuments. */
    @get:JsonProperty("documentUrl")
    val documentUrl: kotlin.String? = null,

    /* Archivflag des Angebots */
    @get:JsonProperty("archived")
    val archived: kotlin.Boolean? = null,

    /* Kundennummer des Angebots */
    @get:JsonProperty("customerNumber")
    val customerNumber: kotlin.String? = null,

    /* Ersteller des Angebots */
    @get:JsonProperty("creator")
    val creator: kotlin.String? = null,

    /* Gesamtbetrag des Angebots (brutto) */
    @get:JsonProperty("totalPrice")
    val totalPrice: java.math.BigDecimal? = null

) {


}

