/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import de.itscope.api.dto.LineItemAddress

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param referencedAddress 
 */


data class ReferencedAddresses (

    @get:JsonProperty("referencedAddress")
    val referencedAddress: kotlin.collections.List<LineItemAddress>? = null

) {


}

