/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import de.itscope.api.dto.IExportFieldObject

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param fields 
 * @param fieldIds 
 * @param fieldHeaders 
 */


data class RowDefinitionObject (

    @get:JsonProperty("fields")
    val fields: kotlin.collections.List<IExportFieldObject>? = null,

    @get:JsonProperty("fieldIds")
    val fieldIds: kotlin.collections.List<kotlin.String>? = null,

    @get:JsonProperty("fieldHeaders")
    val fieldHeaders: kotlin.collections.List<kotlin.String>? = null

) {


}

