/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Preisinformatinen über Staffelpreise
 *
 * @param supplierItemRefId Referenz auf die Bezugsquelle
 * @param scale Skalierung, ab wann Staffelpreis gilt
 * @param price Staffelpreis
 */


data class ScaledPriceInfo (

    /* Referenz auf die Bezugsquelle */
    @get:JsonProperty("supplierItemRefId")
    val supplierItemRefId: kotlin.Long,

    /* Skalierung, ab wann Staffelpreis gilt */
    @get:JsonProperty("scale")
    val scale: kotlin.Int,

    /* Staffelpreis */
    @get:JsonProperty("price")
    val price: java.math.BigDecimal

) {


}

