/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Auflistung aller Verpackungsinformationen wenn vom Lieferant gesetzt
 *
 * @param contentUnit Einheit der Inhalte einer Verpackung
 * @param intervalQuantity Zahl, die angibt, in welcher Staffelung der Artikel bestellt werden kann (in Bestelleinheiten)
 * @param minQuantity Minimale Anzahl an Verpackungseinheiten um eine Bestellung auszulösen
 * @param numberContentUnitPerOrderUnit Anzahl der Inhalte einer Verpackungseinheit
 * @param orderUnit Verpackungseinheit
 * @param priceQuantity Anzahl der Verpackungseinheiten für einen gegebenen Preis
 * @param supplierPackingQuantity Anzahl der Verpackungseinheiten die ein Lieferant in einer Bestellung zur Verfügung stellt
 */


data class SupplierPackagingInfo (

    /* Einheit der Inhalte einer Verpackung */
    @get:JsonProperty("contentUnit")
    val contentUnit: kotlin.String? = null,

    /* Zahl, die angibt, in welcher Staffelung der Artikel bestellt werden kann (in Bestelleinheiten) */
    @get:JsonProperty("intervalQuantity")
    val intervalQuantity: kotlin.Int? = null,

    /* Minimale Anzahl an Verpackungseinheiten um eine Bestellung auszulösen */
    @get:JsonProperty("minQuantity")
    val minQuantity: kotlin.Int? = null,

    /* Anzahl der Inhalte einer Verpackungseinheit */
    @get:JsonProperty("numberContentUnitPerOrderUnit")
    val numberContentUnitPerOrderUnit: kotlin.Int? = null,

    /* Verpackungseinheit */
    @get:JsonProperty("orderUnit")
    val orderUnit: kotlin.String? = null,

    /* Anzahl der Verpackungseinheiten für einen gegebenen Preis */
    @get:JsonProperty("priceQuantity")
    val priceQuantity: kotlin.Int? = null,

    /* Anzahl der Verpackungseinheiten die ein Lieferant in einer Bestellung zur Verfügung stellt */
    @get:JsonProperty("supplierPackingQuantity")
    val supplierPackingQuantity: kotlin.Int? = null

) {


}

