/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Lieferant einer Bezugsquelle.
 *
 * @param id Eindeutiger Key
 * @param name Bezeichner des Lieferanten
 * @param deeplink URL, Link auf den Lieferanten innerhalb der ITscope Plattform
 * @param customerAccountNumber Kundennummer im Falle einer Partnerschaft. Kann als Filter verwendet werden, um zu ermitteln ob zu diesem Lieferanten eine Partnerschaft existiert
 * @param orderAccountNumber Bestellkundennummer für die API, falls nicht vorhanden wird die Kundennummer zurückgegeben.
 * @param weeeRegNo Die WEEE-Reg.-Nr. des Lieferanten (nach §6 ElektroG)
 */


data class Supplier (

    /* Eindeutiger Key */
    @get:JsonProperty("id")
    val id: kotlin.Long,

    /* Bezeichner des Lieferanten */
    @get:JsonProperty("name")
    val name: kotlin.String,

    /* URL, Link auf den Lieferanten innerhalb der ITscope Plattform */
    @get:JsonProperty("deeplink")
    val deeplink: kotlin.String,

    /* Kundennummer im Falle einer Partnerschaft. Kann als Filter verwendet werden, um zu ermitteln ob zu diesem Lieferanten eine Partnerschaft existiert */
    @get:JsonProperty("customerAccountNumber")
    val customerAccountNumber: kotlin.String? = null,

    /* Bestellkundennummer für die API, falls nicht vorhanden wird die Kundennummer zurückgegeben. */
    @get:JsonProperty("orderAccountNumber")
    val orderAccountNumber: kotlin.String? = null,

    /* Die WEEE-Reg.-Nr. des Lieferanten (nach §6 ElektroG) */
    @get:JsonProperty("weeeRegNo")
    val weeeRegNo: kotlin.String? = null

) {


}

