/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import de.itscope.api.dto.ContractParameter
import de.itscope.api.dto.Project
import de.itscope.api.dto.ScaledPriceInfo
import de.itscope.api.dto.SupplierPackagingInfo

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Bezugsquelle eines ITscope-Produkts. Ein konkretes Angebot eines auf ITscope gelisteten Distributors.
 *
 * @param id Eindeutiger Key
 * @param supplierId Verweist 1:1 auf Supplier.id
 * @param conditionId Numerischer Code des <a href=\"https://guide.itscope.com/kb/artikelzustandcodes/\">Zustand des Artikels</a>
 * @param conditionName <a href=\"https://guide.itscope.com/kb/artikelzustandcodes/\">Zustand des Artikels</a> (neu, gebraucht, B-Ware, Refurbished, usw.)
 * @param eolProduct Kennung: Auslaufartikel
 * @param matchQuality <a href=\"https://guide.itscope.com/kb/zuordnungsqualitaet/\">Zuordnungsqualität</a> des Artikels zum ITscope-Produktkatalog
 * @param eanValid Flag, ob die EAN des Lieferanten valide nach den EAN-Kriterien ist
 * @param specialOffer Flag, ob Artikel Sonderangebot ist
 * @param ean EAN-Angabe des Lieferanten
 * @param manufacturerSKU Hersteller-Artikelnummer-Angabe des Lieferanten (muss nicht mit ITscope übereinstimmen)
 * @param supplierSKU Produktnummer des Lieferanten
 * @param supplierName Name des Lieferanten
 * @param manufacturerName Herstellername wie beim Lieferant angegeben
 * @param productName Genauer Bezeichner des Artikels, wie vom Lieferanten übermittelt
 * @param longDescription Erweiterte Artikelbeschreibung des Lieferanten
 * @param promotion Name der Promo-Aktion des Lieferanten
 * @param vat MwSt-Satz für den Artikel
 * @param copyrightLevy Urheberrechtsabgabe
 * @param customsTariffNumber Zolltarifnummer
 * @param countryOfOrigin Ursprungsland des Artikels
 * @param grossDimX LÄnge des Produkts inklusive Maßeinheit
 * @param grossDimY Höhe des Produks inklusive Maßeinheit
 * @param grossDimZ Breite des Produkts inklusive Maßeinheit
 * @param warrantyText Garantieangaben des Lieferanten
 * @param deeplink Link zum Artikel beim Lieferanten
 * @param recommendedRetailPriceNet UVP-Angabe des Lieferanten
 * @param price Preis
 * @param priceCalc Kalkulierter Preis, auf Grundlage der individuellen <a href=\"https://guide.itscope.com/kbtopic/preiskalkulation/\">Preiskalkulation</a>
 * @param currencyCode Währungseinheit, die für diese Preisinformation gilt
 * @param priceCalcVat Umsatzsteuersatz, der zur Berechnung des <a href=\"https://guide.itscope.com/kb/herkunft-der-preis-und-bestandsinformation/\">kalkulierten Preises</a> benutzt wurde
 * @param priceLastUpdate Zeitpunkt der letzten Aktualisierung der Preisinformation
 * @param stockSupplierText Bestandsinformation zur Bezugsquelle, wie vom Lieferanten übermittelt
 * @param stockStatus Numerischer Schlüssel des <a href=\"https://guide.itscope.com/kb/verfuegbarkeitsstatus/\">Lieferstatus dieser Bestandsinformation</a>
 * @param stockStatusText <a href=\"https://guide.itscope.com/kb/verfuegbarkeitsstatus/\">Lieferstatus dieser Bestandsinformation</a>, z.B. \"auf Lager\" oder \"im Außenlager\"
 * @param stock Bestandsmenge
 * @param externalStock Im Außenlager befindliche Bestandsmenge (Zusatzinformation einiger Lieferanten in Strukturen des Lieferstatus \"auf Lager\")
 * @param incomingStock Im Zulauf befindliche Bestandsmenge  (Zusatzinformation einiger Lieferanten in Strukturen des Lieferstatus \"auf Lager\")
 * @param stockAvailabilityDate Liefertermin für nicht auf Lager befindliche Ware
 * @param lastStockUpdate Zeitpunkt der letzten Aktualisierung der Bestandsinformation
 * @param contractTypeId Der <a href=\"https://guide.itscope.com/kb/produktart/\">Vertragstyp</a> bei Lizenz- und Serviceprodukten
 * @param contractTypeName Der Name des <a href=\"https://guide.itscope.com/kb/produktart/\">Vertragstyps</a> bei Lizenz- und Serviceprodukten
 * @param priceBillingPeriod Beschreibt die Länge des Zyklus des Abrechnungszeitraums
 * @param priceBillingPeriodUnit Beschreibt die Zeiteinheit des Abrechnungszeitraums (z.B. \"Years\", \"Months\")
 * @param priceSubscriptionPeriod Beschreibt die Länge der Vertragsdauer
 * @param priceSubscriptionPeriodUnit Beschreibt die Zeiteinheit der Vertragsdauer (z.B. \"Years\", \"Months\")
 * @param weeeRegNo Die WEEE-Reg.-Nr. des Artikels (nach §6 ElektroG)
 * @param contractParameter 
 * @param project 
 * @param supplierPackagingInfo 
 * @param scaledPriceInfo 
 */


data class SupplierItem (

    /* Eindeutiger Key */
    @get:JsonProperty("id")
    val id: kotlin.Long,

    /* Verweist 1:1 auf Supplier.id */
    @get:JsonProperty("supplierId")
    val supplierId: kotlin.Long,

    /* Numerischer Code des <a href=\"https://guide.itscope.com/kb/artikelzustandcodes/\">Zustand des Artikels</a> */
    @get:JsonProperty("conditionId")
    val conditionId: kotlin.Int,

    /* <a href=\"https://guide.itscope.com/kb/artikelzustandcodes/\">Zustand des Artikels</a> (neu, gebraucht, B-Ware, Refurbished, usw.) */
    @get:JsonProperty("conditionName")
    val conditionName: kotlin.String,

    /* Kennung: Auslaufartikel */
    @get:JsonProperty("eolProduct")
    val eolProduct: kotlin.Boolean,

    /* <a href=\"https://guide.itscope.com/kb/zuordnungsqualitaet/\">Zuordnungsqualität</a> des Artikels zum ITscope-Produktkatalog */
    @get:JsonProperty("matchQuality")
    val matchQuality: kotlin.Int,

    /* Flag, ob die EAN des Lieferanten valide nach den EAN-Kriterien ist */
    @get:JsonProperty("eanValid")
    val eanValid: kotlin.Boolean,

    /* Flag, ob Artikel Sonderangebot ist */
    @get:JsonProperty("specialOffer")
    val specialOffer: kotlin.Boolean,

    /* EAN-Angabe des Lieferanten */
    @get:JsonProperty("ean")
    val ean: kotlin.String? = null,

    /* Hersteller-Artikelnummer-Angabe des Lieferanten (muss nicht mit ITscope übereinstimmen) */
    @get:JsonProperty("manufacturerSKU")
    val manufacturerSKU: kotlin.String? = null,

    /* Produktnummer des Lieferanten */
    @get:JsonProperty("supplierSKU")
    val supplierSKU: kotlin.String? = null,

    /* Name des Lieferanten */
    @get:JsonProperty("supplierName")
    val supplierName: kotlin.String? = null,

    /* Herstellername wie beim Lieferant angegeben */
    @get:JsonProperty("manufacturerName")
    val manufacturerName: kotlin.String? = null,

    /* Genauer Bezeichner des Artikels, wie vom Lieferanten übermittelt */
    @get:JsonProperty("productName")
    val productName: kotlin.String? = null,

    /* Erweiterte Artikelbeschreibung des Lieferanten */
    @get:JsonProperty("longDescription")
    val longDescription: kotlin.String? = null,

    /* Name der Promo-Aktion des Lieferanten */
    @get:JsonProperty("promotion")
    val promotion: kotlin.String? = null,

    /* MwSt-Satz für den Artikel */
    @get:JsonProperty("vat")
    val vat: kotlin.Int? = null,

    /* Urheberrechtsabgabe */
    @get:JsonProperty("copyrightLevy")
    val copyrightLevy: kotlin.Double? = null,

    /* Zolltarifnummer */
    @get:JsonProperty("customsTariffNumber")
    val customsTariffNumber: kotlin.String? = null,

    /* Ursprungsland des Artikels */
    @get:JsonProperty("countryOfOrigin")
    val countryOfOrigin: kotlin.String? = null,

    /* LÄnge des Produkts inklusive Maßeinheit */
    @get:JsonProperty("grossDimX")
    val grossDimX: kotlin.Double? = null,

    /* Höhe des Produks inklusive Maßeinheit */
    @get:JsonProperty("grossDimY")
    val grossDimY: kotlin.Double? = null,

    /* Breite des Produkts inklusive Maßeinheit */
    @get:JsonProperty("grossDimZ")
    val grossDimZ: kotlin.Double? = null,

    /* Garantieangaben des Lieferanten */
    @get:JsonProperty("warrantyText")
    val warrantyText: kotlin.String? = null,

    /* Link zum Artikel beim Lieferanten */
    @get:JsonProperty("deeplink")
    val deeplink: kotlin.String? = null,

    /* UVP-Angabe des Lieferanten */
    @get:JsonProperty("recommendedRetailPriceNet")
    val recommendedRetailPriceNet: kotlin.Double? = null,

    /* Preis */
    @get:JsonProperty("price")
    val price: java.math.BigDecimal? = null,

    /* Kalkulierter Preis, auf Grundlage der individuellen <a href=\"https://guide.itscope.com/kbtopic/preiskalkulation/\">Preiskalkulation</a> */
    @get:JsonProperty("priceCalc")
    val priceCalc: java.math.BigDecimal? = null,

    /* Währungseinheit, die für diese Preisinformation gilt */
    @get:JsonProperty("currencyCode")
    val currencyCode: kotlin.String? = null,

    /* Umsatzsteuersatz, der zur Berechnung des <a href=\"https://guide.itscope.com/kb/herkunft-der-preis-und-bestandsinformation/\">kalkulierten Preises</a> benutzt wurde */
    @get:JsonProperty("priceCalcVat")
    val priceCalcVat: java.math.BigDecimal? = null,

    /* Zeitpunkt der letzten Aktualisierung der Preisinformation */
    @get:JsonProperty("priceLastUpdate")
    val priceLastUpdate: java.time.OffsetDateTime? = null,

    /* Bestandsinformation zur Bezugsquelle, wie vom Lieferanten übermittelt */
    @get:JsonProperty("stockSupplierText")
    val stockSupplierText: kotlin.String? = null,

    /* Numerischer Schlüssel des <a href=\"https://guide.itscope.com/kb/verfuegbarkeitsstatus/\">Lieferstatus dieser Bestandsinformation</a> */
    @get:JsonProperty("stockStatus")
    val stockStatus: kotlin.Int? = null,

    /* <a href=\"https://guide.itscope.com/kb/verfuegbarkeitsstatus/\">Lieferstatus dieser Bestandsinformation</a>, z.B. \"auf Lager\" oder \"im Außenlager\" */
    @get:JsonProperty("stockStatusText")
    val stockStatusText: kotlin.String? = null,

    /* Bestandsmenge */
    @get:JsonProperty("stock")
    val stock: kotlin.Int? = null,

    /* Im Außenlager befindliche Bestandsmenge (Zusatzinformation einiger Lieferanten in Strukturen des Lieferstatus \"auf Lager\") */
    @get:JsonProperty("externalStock")
    val externalStock: kotlin.Int? = null,

    /* Im Zulauf befindliche Bestandsmenge  (Zusatzinformation einiger Lieferanten in Strukturen des Lieferstatus \"auf Lager\") */
    @get:JsonProperty("incomingStock")
    val incomingStock: kotlin.Int? = null,

    /* Liefertermin für nicht auf Lager befindliche Ware */
    @get:JsonProperty("stockAvailabilityDate")
    val stockAvailabilityDate: java.time.OffsetDateTime? = null,

    /* Zeitpunkt der letzten Aktualisierung der Bestandsinformation */
    @get:JsonProperty("lastStockUpdate")
    val lastStockUpdate: java.time.OffsetDateTime? = null,

    /* Der <a href=\"https://guide.itscope.com/kb/produktart/\">Vertragstyp</a> bei Lizenz- und Serviceprodukten */
    @get:JsonProperty("contractTypeId")
    val contractTypeId: kotlin.Int? = null,

    /* Der Name des <a href=\"https://guide.itscope.com/kb/produktart/\">Vertragstyps</a> bei Lizenz- und Serviceprodukten */
    @get:JsonProperty("contractTypeName")
    val contractTypeName: kotlin.String? = null,

    /* Beschreibt die Länge des Zyklus des Abrechnungszeitraums */
    @get:JsonProperty("priceBillingPeriod")
    val priceBillingPeriod: kotlin.Int? = null,

    /* Beschreibt die Zeiteinheit des Abrechnungszeitraums (z.B. \"Years\", \"Months\") */
    @get:JsonProperty("priceBillingPeriodUnit")
    val priceBillingPeriodUnit: kotlin.String? = null,

    /* Beschreibt die Länge der Vertragsdauer */
    @get:JsonProperty("priceSubscriptionPeriod")
    val priceSubscriptionPeriod: kotlin.Int? = null,

    /* Beschreibt die Zeiteinheit der Vertragsdauer (z.B. \"Years\", \"Months\") */
    @get:JsonProperty("priceSubscriptionPeriodUnit")
    val priceSubscriptionPeriodUnit: kotlin.String? = null,

    /* Die WEEE-Reg.-Nr. des Artikels (nach §6 ElektroG) */
    @get:JsonProperty("weeeRegNo")
    val weeeRegNo: kotlin.String? = null,

    @get:JsonProperty("contractParameter")
    val contractParameter: kotlin.collections.List<ContractParameter>? = null,

    @get:JsonProperty("project")
    val project: kotlin.collections.List<Project>? = null,

    @get:JsonProperty("supplierPackagingInfo")
    val supplierPackagingInfo: SupplierPackagingInfo? = null,

    @get:JsonProperty("scaledPriceInfo")
    val scaledPriceInfo: kotlin.collections.List<ScaledPriceInfo>? = null

) {


}

