/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param excludeWeeNumbers 
 * @param projectBundleInformationVisible 
 */


data class TableProviderSettings (

    @get:JsonProperty("excludeWeeNumbers")
    val excludeWeeNumbers: kotlin.Boolean? = null,

    @get:JsonProperty("projectBundleInformationVisible")
    val projectBundleInformationVisible: kotlin.Boolean? = null

) {


}

