/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.client

import com.fasterxml.jackson.annotation.JsonProperty

import org.springframework.web.reactive.function.client.WebClient
import org.springframework.web.reactive.function.client.WebClientResponseException
import org.springframework.http.codec.json.Jackson2JsonDecoder
import org.springframework.http.codec.json.Jackson2JsonEncoder
import org.springframework.http.ResponseEntity
import org.springframework.http.MediaType
import reactor.core.publisher.Mono
import org.springframework.util.LinkedMultiValueMap

import de.itscope.api.dto.Deal
import org.openapitools.client.infrastructure.*

class BusinessdealsPurchaseApi(client: WebClient) : ApiClient(client) {

    constructor(baseUrl: String) : this(WebClient.builder()
        .baseUrl(baseUrl)
        .codecs {
            it.defaultCodecs().jackson2JsonEncoder(Jackson2JsonEncoder(Serializer.jacksonObjectMapper, MediaType.APPLICATION_JSON))
            it.defaultCodecs().jackson2JsonDecoder(Jackson2JsonDecoder(Serializer.jacksonObjectMapper, MediaType.APPLICATION_JSON))
        }
        .build()
    )

    /**
     * enum for parameter view
     */
    enum class ViewGetOrderList(val value: kotlin.String) {
        @JsonProperty(value = "deal") deal("deal")
    }

    /**
     * enum for parameter type
     */
    enum class TypeGetOrderList(val value: kotlin.String) {
        @JsonProperty(value = "xml") xml("xml"),
        @JsonProperty(value = "json") json("json")
    }

    /**
     * enum for parameter archiv
     */
    enum class ArchivGetOrderList(val value: kotlin.String) {
        @JsonProperty(value = "ARCHIVED") ARCHIVED("ARCHIVED"),
        @JsonProperty(value = "NOTARCHIVED") NOTARCHIVED("NOTARCHIVED")
    }

    /**
     * enum for parameter sort
     */
    enum class SortGetOrderList(val value: kotlin.String) {
        @JsonProperty(value = "LAST_MODIFIED") LAST_MODIFIED("LAST_MODIFIED"),
        @JsonProperty(value = "SENT_DESC") SENT_DESC("SENT_DESC"),
        @JsonProperty(value = "SENT_ASC") SENT_ASC("SENT_ASC"),
        @JsonProperty(value = "SUPPLIER") SUPPLIER("SUPPLIER"),
        @JsonProperty(value = "ID") ID("ID")
    }


    @Throws(WebClientResponseException::class)
    fun getOrderList(view: ViewGetOrderList, type: TypeGetOrderList, archiv: ArchivGetOrderList, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, sort: SortGetOrderList? = SortGetOrderList.LAST_MODIFIED, page: kotlin.Int? = 1): Mono<kotlin.collections.List<Deal>> {
        return getOrderListWithHttpInfo(view = view, type = type, archiv = archiv, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, sort = sort, page = page)
            .map { it.body }
    }

    @Throws(WebClientResponseException::class)
    fun getOrderListWithHttpInfo(view: ViewGetOrderList, type: TypeGetOrderList, archiv: ArchivGetOrderList, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, sort: SortGetOrderList? = SortGetOrderList.LAST_MODIFIED, page: kotlin.Int? = 1): Mono<ResponseEntity<kotlin.collections.List<Deal>>> {
        val localVariableConfig = getOrderListRequestConfig(view = view, type = type, archiv = archiv, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, sort = sort, page = page)
        return request<Unit, kotlin.collections.List<Deal>>(
            localVariableConfig
        )
    }

    fun getOrderListRequestConfig(view: ViewGetOrderList, type: TypeGetOrderList, archiv: ArchivGetOrderList, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, sort: SortGetOrderList? = SortGetOrderList.LAST_MODIFIED, page: kotlin.Int? = 1) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (lastUpdateDateFrom != null) {
                    put("lastUpdateDateFrom", listOf(lastUpdateDateFrom.toString()))
                }
                if (lastUpdateDateTo != null) {
                    put("lastUpdateDateTo", listOf(lastUpdateDateTo.toString()))
                }
                put("archiv", listOf(archiv.toString()))
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/xml, application/json"

        val params = mutableMapOf<String, Any>(
            "view" to view.value,
            "type" to type.value,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/business/deals/purchase/{view}.{type}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun newDeal(body: kotlin.Any? = null): Mono<Unit> {
        return newDealWithHttpInfo(body = body)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun newDealWithHttpInfo(body: kotlin.Any? = null): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = newDealRequestConfig(body = body)
        return request<kotlin.Any, Unit>(
            localVariableConfig
        )
    }

    fun newDealRequestConfig(body: kotlin.Any? = null) : RequestConfig<kotlin.Any> {
        val localVariableBody = body
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/xml"
        localVariableHeaders["Content-Type"] = "text/xml"
        
        val params = mutableMapOf<String, Any>(
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/business/deals/purchase/send",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter view
     */
    enum class ViewSearchOrders(val value: kotlin.String) {
        @JsonProperty(value = "deal") deal("deal")
    }

    /**
     * enum for parameter type
     */
    enum class TypeSearchOrders(val value: kotlin.String) {
        @JsonProperty(value = "xml") xml("xml"),
        @JsonProperty(value = "json") json("json")
    }

    /**
     * enum for parameter archiv
     */
    enum class ArchivSearchOrders(val value: kotlin.String) {
        @JsonProperty(value = "ARCHIVED") ARCHIVED("ARCHIVED"),
        @JsonProperty(value = "NOTARCHIVED") NOTARCHIVED("NOTARCHIVED")
    }

    /**
     * enum for parameter sort
     */
    enum class SortSearchOrders(val value: kotlin.String) {
        @JsonProperty(value = "LAST_MODIFIED") LAST_MODIFIED("LAST_MODIFIED"),
        @JsonProperty(value = "DATE_DESC") DATE_DESC("DATE_DESC"),
        @JsonProperty(value = "DATE_ASC") DATE_ASC("DATE_ASC"),
        @JsonProperty(value = "SUPPLIER") SUPPLIER("SUPPLIER"),
        @JsonProperty(value = "ID") ID("ID")
    }


    @Throws(WebClientResponseException::class)
    fun searchOrders(view: ViewSearchOrders, type: TypeSearchOrders, filter: kotlin.String, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, archiv: ArchivSearchOrders? = ArchivSearchOrders.NOTARCHIVED, sort: SortSearchOrders? = SortSearchOrders.LAST_MODIFIED, page: kotlin.Int? = 1): Mono<kotlin.collections.List<Deal>> {
        return searchOrdersWithHttpInfo(view = view, type = type, filter = filter, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, archiv = archiv, sort = sort, page = page)
            .map { it.body }
    }

    @Throws(WebClientResponseException::class)
    fun searchOrdersWithHttpInfo(view: ViewSearchOrders, type: TypeSearchOrders, filter: kotlin.String, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, archiv: ArchivSearchOrders? = ArchivSearchOrders.NOTARCHIVED, sort: SortSearchOrders? = SortSearchOrders.LAST_MODIFIED, page: kotlin.Int? = 1): Mono<ResponseEntity<kotlin.collections.List<Deal>>> {
        val localVariableConfig = searchOrdersRequestConfig(view = view, type = type, filter = filter, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, archiv = archiv, sort = sort, page = page)
        return request<Unit, kotlin.collections.List<Deal>>(
            localVariableConfig
        )
    }

    fun searchOrdersRequestConfig(view: ViewSearchOrders, type: TypeSearchOrders, filter: kotlin.String, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, archiv: ArchivSearchOrders? = ArchivSearchOrders.NOTARCHIVED, sort: SortSearchOrders? = SortSearchOrders.LAST_MODIFIED, page: kotlin.Int? = 1) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (lastUpdateDateFrom != null) {
                    put("lastUpdateDateFrom", listOf(lastUpdateDateFrom.toString()))
                }
                if (lastUpdateDateTo != null) {
                    put("lastUpdateDateTo", listOf(lastUpdateDateTo.toString()))
                }
                if (archiv != null) {
                    put("archiv", listOf(archiv.toString()))
                }
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/xml, application/json"

        val params = mutableMapOf<String, Any>(
            "view" to view.value,
            "type" to type.value,
            "filter" to filter,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/business/deals/purchase/search/{filter}/{view}.{type}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

}
