/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.client

import com.fasterxml.jackson.annotation.JsonProperty

import org.springframework.web.reactive.function.client.WebClient
import org.springframework.web.reactive.function.client.WebClientResponseException
import org.springframework.http.codec.json.Jackson2JsonDecoder
import org.springframework.http.codec.json.Jackson2JsonEncoder
import org.springframework.http.ResponseEntity
import org.springframework.http.MediaType
import reactor.core.publisher.Mono
import org.springframework.util.LinkedMultiValueMap

import de.itscope.api.dto.Deal
import org.openapitools.client.infrastructure.*

class BusinessdealsApi(client: WebClient) : ApiClient(client) {

    constructor(baseUrl: String) : this(WebClient.builder()
        .baseUrl(baseUrl)
        .codecs {
            it.defaultCodecs().jackson2JsonEncoder(Jackson2JsonEncoder(Serializer.jacksonObjectMapper, MediaType.APPLICATION_JSON))
            it.defaultCodecs().jackson2JsonDecoder(Jackson2JsonDecoder(Serializer.jacksonObjectMapper, MediaType.APPLICATION_JSON))
        }
        .build()
    )


    @Throws(WebClientResponseException::class)
    fun adviseDeal(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<Unit> {
        return adviseDealWithHttpInfo(dealId = dealId, suppressMail = suppressMail)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun adviseDealWithHttpInfo(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = adviseDealRequestConfig(dealId = dealId, suppressMail = suppressMail)
        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    fun adviseDealRequestConfig(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (suppressMail != null) {
                    put("suppressMail", listOf(suppressMail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/business/deals/advise/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun adviseDealPost(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.String? = null): Mono<Unit> {
        return adviseDealPostWithHttpInfo(dealId = dealId, suppressMail = suppressMail, body = body)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun adviseDealPostWithHttpInfo(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.String? = null): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = adviseDealPostRequestConfig(dealId = dealId, suppressMail = suppressMail, body = body)
        return request<kotlin.String, Unit>(
            localVariableConfig
        )
    }

    fun adviseDealPostRequestConfig(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.String? = null) : RequestConfig<kotlin.String> {
        val localVariableBody = body
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (suppressMail != null) {
                    put("suppressMail", listOf(suppressMail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/business/deals/advise/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun archiveDeal(dealId: kotlin.String): Mono<Unit> {
        return archiveDealWithHttpInfo(dealId = dealId)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun archiveDealWithHttpInfo(dealId: kotlin.String): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = archiveDealRequestConfig(dealId = dealId)
        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    fun archiveDealRequestConfig(dealId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/business/deals/archive/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun cancelDeal(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<Unit> {
        return cancelDealWithHttpInfo(dealId = dealId, suppressMail = suppressMail)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun cancelDealWithHttpInfo(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = cancelDealRequestConfig(dealId = dealId, suppressMail = suppressMail)
        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    fun cancelDealRequestConfig(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (suppressMail != null) {
                    put("suppressMail", listOf(suppressMail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/business/deals/cancel/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun confirmDeal(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<Unit> {
        return confirmDealWithHttpInfo(dealId = dealId, suppressMail = suppressMail)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun confirmDealWithHttpInfo(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = confirmDealRequestConfig(dealId = dealId, suppressMail = suppressMail)
        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    fun confirmDealRequestConfig(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (suppressMail != null) {
                    put("suppressMail", listOf(suppressMail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/business/deals/confirm/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun confirmDealPost(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.String? = null): Mono<Unit> {
        return confirmDealPostWithHttpInfo(dealId = dealId, suppressMail = suppressMail, body = body)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun confirmDealPostWithHttpInfo(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.String? = null): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = confirmDealPostRequestConfig(dealId = dealId, suppressMail = suppressMail, body = body)
        return request<kotlin.String, Unit>(
            localVariableConfig
        )
    }

    fun confirmDealPostRequestConfig(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.String? = null) : RequestConfig<kotlin.String> {
        val localVariableBody = body
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (suppressMail != null) {
                    put("suppressMail", listOf(suppressMail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/xml"
        localVariableHeaders["Content-Type"] = "text/xml"
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/business/deals/confirm/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter view
     */
    enum class ViewGetDealByOrderId(val value: kotlin.String) {
        @JsonProperty(value = "deal") deal("deal")
    }

    /**
     * enum for parameter type
     */
    enum class TypeGetDealByOrderId(val value: kotlin.String) {
        @JsonProperty(value = "xml") xml("xml"),
        @JsonProperty(value = "json") json("json"),
        @JsonProperty(value = "pdf") pdf("pdf")
    }


    @Throws(WebClientResponseException::class)
    fun getDealByOrderId(dealId: kotlin.String, view: ViewGetDealByOrderId, type: TypeGetDealByOrderId): Mono<kotlin.collections.List<Deal>> {
        return getDealByOrderIdWithHttpInfo(dealId = dealId, view = view, type = type)
            .map { it.body }
    }

    @Throws(WebClientResponseException::class)
    fun getDealByOrderIdWithHttpInfo(dealId: kotlin.String, view: ViewGetDealByOrderId, type: TypeGetDealByOrderId): Mono<ResponseEntity<kotlin.collections.List<Deal>>> {
        val localVariableConfig = getDealByOrderIdRequestConfig(dealId = dealId, view = view, type = type)
        return request<Unit, kotlin.collections.List<Deal>>(
            localVariableConfig
        )
    }

    fun getDealByOrderIdRequestConfig(dealId: kotlin.String, view: ViewGetDealByOrderId, type: TypeGetDealByOrderId) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/xml, application/json"

        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
            "view" to view.value,
            "type" to type.value,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/business/deals/{dealId}/{view}.{type}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter view
     */
    enum class ViewGetDealList(val value: kotlin.String) {
        @JsonProperty(value = "deal") deal("deal")
    }

    /**
     * enum for parameter type
     */
    enum class TypeGetDealList(val value: kotlin.String) {
        @JsonProperty(value = "xml") xml("xml"),
        @JsonProperty(value = "json") json("json")
    }

    /**
     * enum for parameter archiv
     */
    enum class ArchivGetDealList(val value: kotlin.String) {
        @JsonProperty(value = "ARCHIVED") ARCHIVED("ARCHIVED"),
        @JsonProperty(value = "NOTARCHIVED") NOTARCHIVED("NOTARCHIVED")
    }

    /**
     * enum for parameter businessType
     */
    enum class BusinessTypeGetDealList(val value: kotlin.String) {
        @JsonProperty(value = "PURCHASE") PURCHASE("PURCHASE"),
        @JsonProperty(value = "SALE") SALE("SALE")
    }

    /**
     * enum for parameter sort
     */
    enum class SortGetDealList(val value: kotlin.String) {
        @JsonProperty(value = "LAST_MODIFIED") LAST_MODIFIED("LAST_MODIFIED"),
        @JsonProperty(value = "SENT_DESC") SENT_DESC("SENT_DESC"),
        @JsonProperty(value = "SENT_ASC") SENT_ASC("SENT_ASC"),
        @JsonProperty(value = "SUPPLIER") SUPPLIER("SUPPLIER"),
        @JsonProperty(value = "ID") ID("ID")
    }


    @Throws(WebClientResponseException::class)
    @Deprecated(message = "This operation is deprecated.")
    fun getDealList(view: ViewGetDealList, type: TypeGetDealList, archiv: ArchivGetDealList, businessType: BusinessTypeGetDealList, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, sort: SortGetDealList? = SortGetDealList.LAST_MODIFIED, page: kotlin.Int? = 1): Mono<kotlin.collections.List<Deal>> {
        return getDealListWithHttpInfo(view = view, type = type, archiv = archiv, businessType = businessType, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, sort = sort, page = page)
            .map { it.body }
    }

    @Throws(WebClientResponseException::class)
    @Deprecated(message = "This operation is deprecated.")
    fun getDealListWithHttpInfo(view: ViewGetDealList, type: TypeGetDealList, archiv: ArchivGetDealList, businessType: BusinessTypeGetDealList, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, sort: SortGetDealList? = SortGetDealList.LAST_MODIFIED, page: kotlin.Int? = 1): Mono<ResponseEntity<kotlin.collections.List<Deal>>> {
        val localVariableConfig = getDealListRequestConfig(view = view, type = type, archiv = archiv, businessType = businessType, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, sort = sort, page = page)
        return request<Unit, kotlin.collections.List<Deal>>(
            localVariableConfig
        )
    }

    @Deprecated(message = "This operation is deprecated.")
    fun getDealListRequestConfig(view: ViewGetDealList, type: TypeGetDealList, archiv: ArchivGetDealList, businessType: BusinessTypeGetDealList, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, sort: SortGetDealList? = SortGetDealList.LAST_MODIFIED, page: kotlin.Int? = 1) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (lastUpdateDateFrom != null) {
                    put("lastUpdateDateFrom", listOf(lastUpdateDateFrom.toString()))
                }
                if (lastUpdateDateTo != null) {
                    put("lastUpdateDateTo", listOf(lastUpdateDateTo.toString()))
                }
                put("archiv", listOf(archiv.toString()))
                put("businessType", listOf(businessType.toString()))
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/xml, application/json"

        val params = mutableMapOf<String, Any>(
            "view" to view.value,
            "type" to type.value,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/business/deals/{view}.{type}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter view
     */
    enum class ViewGetDealList1(val value: kotlin.String) {
        @JsonProperty(value = "deal") deal("deal")
    }

    /**
     * enum for parameter type
     */
    enum class TypeGetDealList1(val value: kotlin.String) {
        @JsonProperty(value = "xml") xml("xml"),
        @JsonProperty(value = "json") json("json")
    }

    /**
     * enum for parameter archiv
     */
    enum class ArchivGetDealList1(val value: kotlin.String) {
        @JsonProperty(value = "ARCHIVED") ARCHIVED("ARCHIVED"),
        @JsonProperty(value = "NOTARCHIVED") NOTARCHIVED("NOTARCHIVED")
    }

    /**
     * enum for parameter sort
     */
    enum class SortGetDealList1(val value: kotlin.String) {
        @JsonProperty(value = "LAST_MODIFIED") LAST_MODIFIED("LAST_MODIFIED"),
        @JsonProperty(value = "SENT_DESC") SENT_DESC("SENT_DESC"),
        @JsonProperty(value = "SENT_ASC") SENT_ASC("SENT_ASC"),
        @JsonProperty(value = "SUPPLIER") SUPPLIER("SUPPLIER"),
        @JsonProperty(value = "ID") ID("ID")
    }

    /**
     * enum for parameter testOrder
     */
    enum class TestOrderGetDealList1(val value: kotlin.String) {
        @JsonProperty(value = "true") `true`("true"),
        @JsonProperty(value = "false") `false`("false")
    }


    @Throws(WebClientResponseException::class)
    fun getDealList1(view: ViewGetDealList1, type: TypeGetDealList1, archiv: ArchivGetDealList1, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, sort: SortGetDealList1? = SortGetDealList1.LAST_MODIFIED, page: kotlin.Int? = 1, testOrder: TestOrderGetDealList1? = null): Mono<kotlin.collections.List<Deal>> {
        return getDealList1WithHttpInfo(view = view, type = type, archiv = archiv, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, sort = sort, page = page, testOrder = testOrder)
            .map { it.body }
    }

    @Throws(WebClientResponseException::class)
    fun getDealList1WithHttpInfo(view: ViewGetDealList1, type: TypeGetDealList1, archiv: ArchivGetDealList1, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, sort: SortGetDealList1? = SortGetDealList1.LAST_MODIFIED, page: kotlin.Int? = 1, testOrder: TestOrderGetDealList1? = null): Mono<ResponseEntity<kotlin.collections.List<Deal>>> {
        val localVariableConfig = getDealList1RequestConfig(view = view, type = type, archiv = archiv, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, sort = sort, page = page, testOrder = testOrder)
        return request<Unit, kotlin.collections.List<Deal>>(
            localVariableConfig
        )
    }

    fun getDealList1RequestConfig(view: ViewGetDealList1, type: TypeGetDealList1, archiv: ArchivGetDealList1, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, sort: SortGetDealList1? = SortGetDealList1.LAST_MODIFIED, page: kotlin.Int? = 1, testOrder: TestOrderGetDealList1? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (lastUpdateDateFrom != null) {
                    put("lastUpdateDateFrom", listOf(lastUpdateDateFrom.toString()))
                }
                if (lastUpdateDateTo != null) {
                    put("lastUpdateDateTo", listOf(lastUpdateDateTo.toString()))
                }
                put("archiv", listOf(archiv.toString()))
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (testOrder != null) {
                    put("testOrder", listOf(testOrder.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/xml, application/json"

        val params = mutableMapOf<String, Any>(
            "view" to view.value,
            "type" to type.value,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/business/deals/sales/{view}.{type}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter view
     */
    enum class ViewGetOrderList(val value: kotlin.String) {
        @JsonProperty(value = "deal") deal("deal")
    }

    /**
     * enum for parameter type
     */
    enum class TypeGetOrderList(val value: kotlin.String) {
        @JsonProperty(value = "xml") xml("xml"),
        @JsonProperty(value = "json") json("json")
    }

    /**
     * enum for parameter archiv
     */
    enum class ArchivGetOrderList(val value: kotlin.String) {
        @JsonProperty(value = "ARCHIVED") ARCHIVED("ARCHIVED"),
        @JsonProperty(value = "NOTARCHIVED") NOTARCHIVED("NOTARCHIVED")
    }

    /**
     * enum for parameter sort
     */
    enum class SortGetOrderList(val value: kotlin.String) {
        @JsonProperty(value = "LAST_MODIFIED") LAST_MODIFIED("LAST_MODIFIED"),
        @JsonProperty(value = "SENT_DESC") SENT_DESC("SENT_DESC"),
        @JsonProperty(value = "SENT_ASC") SENT_ASC("SENT_ASC"),
        @JsonProperty(value = "SUPPLIER") SUPPLIER("SUPPLIER"),
        @JsonProperty(value = "ID") ID("ID")
    }


    @Throws(WebClientResponseException::class)
    fun getOrderList(view: ViewGetOrderList, type: TypeGetOrderList, archiv: ArchivGetOrderList, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, sort: SortGetOrderList? = SortGetOrderList.LAST_MODIFIED, page: kotlin.Int? = 1): Mono<kotlin.collections.List<Deal>> {
        return getOrderListWithHttpInfo(view = view, type = type, archiv = archiv, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, sort = sort, page = page)
            .map { it.body }
    }

    @Throws(WebClientResponseException::class)
    fun getOrderListWithHttpInfo(view: ViewGetOrderList, type: TypeGetOrderList, archiv: ArchivGetOrderList, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, sort: SortGetOrderList? = SortGetOrderList.LAST_MODIFIED, page: kotlin.Int? = 1): Mono<ResponseEntity<kotlin.collections.List<Deal>>> {
        val localVariableConfig = getOrderListRequestConfig(view = view, type = type, archiv = archiv, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, sort = sort, page = page)
        return request<Unit, kotlin.collections.List<Deal>>(
            localVariableConfig
        )
    }

    fun getOrderListRequestConfig(view: ViewGetOrderList, type: TypeGetOrderList, archiv: ArchivGetOrderList, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, sort: SortGetOrderList? = SortGetOrderList.LAST_MODIFIED, page: kotlin.Int? = 1) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (lastUpdateDateFrom != null) {
                    put("lastUpdateDateFrom", listOf(lastUpdateDateFrom.toString()))
                }
                if (lastUpdateDateTo != null) {
                    put("lastUpdateDateTo", listOf(lastUpdateDateTo.toString()))
                }
                put("archiv", listOf(archiv.toString()))
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/xml, application/json"

        val params = mutableMapOf<String, Any>(
            "view" to view.value,
            "type" to type.value,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/business/deals/purchase/{view}.{type}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun invoiceDeal(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<Unit> {
        return invoiceDealWithHttpInfo(dealId = dealId, suppressMail = suppressMail)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun invoiceDealWithHttpInfo(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = invoiceDealRequestConfig(dealId = dealId, suppressMail = suppressMail)
        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    fun invoiceDealRequestConfig(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (suppressMail != null) {
                    put("suppressMail", listOf(suppressMail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/business/deals/invoice/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun invoiceDealPost(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.String? = null): Mono<Unit> {
        return invoiceDealPostWithHttpInfo(dealId = dealId, suppressMail = suppressMail, body = body)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun invoiceDealPostWithHttpInfo(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.String? = null): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = invoiceDealPostRequestConfig(dealId = dealId, suppressMail = suppressMail, body = body)
        return request<kotlin.String, Unit>(
            localVariableConfig
        )
    }

    fun invoiceDealPostRequestConfig(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.String? = null) : RequestConfig<kotlin.String> {
        val localVariableBody = body
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (suppressMail != null) {
                    put("suppressMail", listOf(suppressMail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/xml"
        localVariableHeaders["Content-Type"] = "text/xml"
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/business/deals/invoice/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun invoiceDealPostXPdf(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.String? = null): Mono<Unit> {
        return invoiceDealPostXPdfWithHttpInfo(dealId = dealId, suppressMail = suppressMail, body = body)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun invoiceDealPostXPdfWithHttpInfo(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.String? = null): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = invoiceDealPostXPdfRequestConfig(dealId = dealId, suppressMail = suppressMail, body = body)
        return request<kotlin.String, Unit>(
            localVariableConfig
        )
    }

    fun invoiceDealPostXPdfRequestConfig(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.String? = null) : RequestConfig<kotlin.String> {
        val localVariableBody = body
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (suppressMail != null) {
                    put("suppressMail", listOf(suppressMail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/xml"
        localVariableHeaders["Content-Type"] = "text/xml"
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/business/deals/invoicexrechnung/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun invoiceDealPostZugferd1Pdf(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.ByteArray? = null): Mono<Unit> {
        return invoiceDealPostZugferd1PdfWithHttpInfo(dealId = dealId, suppressMail = suppressMail, body = body)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun invoiceDealPostZugferd1PdfWithHttpInfo(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.ByteArray? = null): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = invoiceDealPostZugferd1PdfRequestConfig(dealId = dealId, suppressMail = suppressMail, body = body)
        return request<kotlin.ByteArray, Unit>(
            localVariableConfig
        )
    }

    fun invoiceDealPostZugferd1PdfRequestConfig(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.ByteArray? = null) : RequestConfig<kotlin.ByteArray> {
        val localVariableBody = body
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (suppressMail != null) {
                    put("suppressMail", listOf(suppressMail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/pdf"
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/business/deals/invoicezugferd1/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun invoiceDealPostZugferd2Pdf(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.ByteArray? = null): Mono<Unit> {
        return invoiceDealPostZugferd2PdfWithHttpInfo(dealId = dealId, suppressMail = suppressMail, body = body)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun invoiceDealPostZugferd2PdfWithHttpInfo(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.ByteArray? = null): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = invoiceDealPostZugferd2PdfRequestConfig(dealId = dealId, suppressMail = suppressMail, body = body)
        return request<kotlin.ByteArray, Unit>(
            localVariableConfig
        )
    }

    fun invoiceDealPostZugferd2PdfRequestConfig(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false, body: kotlin.ByteArray? = null) : RequestConfig<kotlin.ByteArray> {
        val localVariableBody = body
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (suppressMail != null) {
                    put("suppressMail", listOf(suppressMail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/pdf"
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/business/deals/invoicezugferd/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun newDeal(body: kotlin.Any? = null): Mono<Unit> {
        return newDealWithHttpInfo(body = body)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun newDealWithHttpInfo(body: kotlin.Any? = null): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = newDealRequestConfig(body = body)
        return request<kotlin.Any, Unit>(
            localVariableConfig
        )
    }

    fun newDealRequestConfig(body: kotlin.Any? = null) : RequestConfig<kotlin.Any> {
        val localVariableBody = body
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/xml"
        localVariableHeaders["Content-Type"] = "text/xml"
        
        val params = mutableMapOf<String, Any>(
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/business/deals/purchase/send",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun newDeal1(testOrder: kotlin.Boolean? = false, body: kotlin.Any? = null): Mono<Unit> {
        return newDeal1WithHttpInfo(testOrder = testOrder, body = body)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun newDeal1WithHttpInfo(testOrder: kotlin.Boolean? = false, body: kotlin.Any? = null): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = newDeal1RequestConfig(testOrder = testOrder, body = body)
        return request<kotlin.Any, Unit>(
            localVariableConfig
        )
    }

    fun newDeal1RequestConfig(testOrder: kotlin.Boolean? = false, body: kotlin.Any? = null) : RequestConfig<kotlin.Any> {
        val localVariableBody = body
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (testOrder != null) {
                    put("testOrder", listOf(testOrder.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/xml"
        localVariableHeaders["Content-Type"] = "text/xml"
        
        val params = mutableMapOf<String, Any>(
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/business/deals/sales/send",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun newDeal2(body: kotlin.Any? = null): Mono<Unit> {
        return newDeal2WithHttpInfo(body = body)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun newDeal2WithHttpInfo(body: kotlin.Any? = null): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = newDeal2RequestConfig(body = body)
        return request<kotlin.Any, Unit>(
            localVariableConfig
        )
    }

    fun newDeal2RequestConfig(body: kotlin.Any? = null) : RequestConfig<kotlin.Any> {
        val localVariableBody = body
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/xml"
        localVariableHeaders["Content-Type"] = "text/xml"
        
        val params = mutableMapOf<String, Any>(
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/business/deals/send",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    @Deprecated(message = "This operation is deprecated.")
    fun newDealDeprecated(distributorId: kotlin.String, body: kotlin.Any? = null): Mono<Unit> {
        return newDealDeprecatedWithHttpInfo(distributorId = distributorId, body = body)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    @Deprecated(message = "This operation is deprecated.")
    fun newDealDeprecatedWithHttpInfo(distributorId: kotlin.String, body: kotlin.Any? = null): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = newDealDeprecatedRequestConfig(distributorId = distributorId, body = body)
        return request<kotlin.Any, Unit>(
            localVariableConfig
        )
    }

    @Deprecated(message = "This operation is deprecated.")
    fun newDealDeprecatedRequestConfig(distributorId: kotlin.String, body: kotlin.Any? = null) : RequestConfig<kotlin.Any> {
        val localVariableBody = body
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/xml"
        localVariableHeaders["Content-Type"] = "text/xml"
        
        val params = mutableMapOf<String, Any>(
            "distributorId" to distributorId,
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/business/deals/send/{distributorId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun orderedElsewhereDeal(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<Unit> {
        return orderedElsewhereDealWithHttpInfo(dealId = dealId, suppressMail = suppressMail)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun orderedElsewhereDealWithHttpInfo(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = orderedElsewhereDealRequestConfig(dealId = dealId, suppressMail = suppressMail)
        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    fun orderedElsewhereDealRequestConfig(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (suppressMail != null) {
                    put("suppressMail", listOf(suppressMail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/business/deals/orderedelsewhere/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun partiallyadviseDeal(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<Unit> {
        return partiallyadviseDealWithHttpInfo(dealId = dealId, suppressMail = suppressMail)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun partiallyadviseDealWithHttpInfo(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = partiallyadviseDealRequestConfig(dealId = dealId, suppressMail = suppressMail)
        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    fun partiallyadviseDealRequestConfig(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (suppressMail != null) {
                    put("suppressMail", listOf(suppressMail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/business/deals/partiallyadvise/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun partiallyinvoiceDeal(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<Unit> {
        return partiallyinvoiceDealWithHttpInfo(dealId = dealId, suppressMail = suppressMail)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun partiallyinvoiceDealWithHttpInfo(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = partiallyinvoiceDealRequestConfig(dealId = dealId, suppressMail = suppressMail)
        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    fun partiallyinvoiceDealRequestConfig(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (suppressMail != null) {
                    put("suppressMail", listOf(suppressMail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/business/deals/partiallyinvoice/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    @Throws(WebClientResponseException::class)
    fun rejectDeal(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<Unit> {
        return rejectDealWithHttpInfo(dealId = dealId, suppressMail = suppressMail)
            .map { Unit }
    }

    @Throws(WebClientResponseException::class)
    fun rejectDealWithHttpInfo(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false): Mono<ResponseEntity<Unit>> {
        val localVariableConfig = rejectDealRequestConfig(dealId = dealId, suppressMail = suppressMail)
        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    fun rejectDealRequestConfig(dealId: kotlin.String, suppressMail: kotlin.Boolean? = false) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (suppressMail != null) {
                    put("suppressMail", listOf(suppressMail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val params = mutableMapOf<String, Any>(
            "dealId" to dealId,
        )

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/business/deals/reject/{dealId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter view
     */
    enum class ViewSearchDeals(val value: kotlin.String) {
        @JsonProperty(value = "deal") deal("deal")
    }

    /**
     * enum for parameter type
     */
    enum class TypeSearchDeals(val value: kotlin.String) {
        @JsonProperty(value = "xml") xml("xml"),
        @JsonProperty(value = "json") json("json")
    }

    /**
     * enum for parameter archiv
     */
    enum class ArchivSearchDeals(val value: kotlin.String) {
        @JsonProperty(value = "ARCHIVED") ARCHIVED("ARCHIVED"),
        @JsonProperty(value = "NOTARCHIVED") NOTARCHIVED("NOTARCHIVED")
    }

    /**
     * enum for parameter sort
     */
    enum class SortSearchDeals(val value: kotlin.String) {
        @JsonProperty(value = "LAST_MODIFIED") LAST_MODIFIED("LAST_MODIFIED"),
        @JsonProperty(value = "DATE_DESC") DATE_DESC("DATE_DESC"),
        @JsonProperty(value = "DATE_ASC") DATE_ASC("DATE_ASC"),
        @JsonProperty(value = "SUPPLIER") SUPPLIER("SUPPLIER"),
        @JsonProperty(value = "ID") ID("ID")
    }

    /**
     * enum for parameter testOrder
     */
    enum class TestOrderSearchDeals(val value: kotlin.String) {
        @JsonProperty(value = "true") `true`("true"),
        @JsonProperty(value = "false") `false`("false")
    }


    @Throws(WebClientResponseException::class)
    fun searchDeals(view: ViewSearchDeals, type: TypeSearchDeals, filter: kotlin.String, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, archiv: ArchivSearchDeals? = ArchivSearchDeals.NOTARCHIVED, sort: SortSearchDeals? = SortSearchDeals.LAST_MODIFIED, page: kotlin.Int? = 1, testOrder: TestOrderSearchDeals? = null): Mono<kotlin.collections.List<Deal>> {
        return searchDealsWithHttpInfo(view = view, type = type, filter = filter, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, archiv = archiv, sort = sort, page = page, testOrder = testOrder)
            .map { it.body }
    }

    @Throws(WebClientResponseException::class)
    fun searchDealsWithHttpInfo(view: ViewSearchDeals, type: TypeSearchDeals, filter: kotlin.String, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, archiv: ArchivSearchDeals? = ArchivSearchDeals.NOTARCHIVED, sort: SortSearchDeals? = SortSearchDeals.LAST_MODIFIED, page: kotlin.Int? = 1, testOrder: TestOrderSearchDeals? = null): Mono<ResponseEntity<kotlin.collections.List<Deal>>> {
        val localVariableConfig = searchDealsRequestConfig(view = view, type = type, filter = filter, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, archiv = archiv, sort = sort, page = page, testOrder = testOrder)
        return request<Unit, kotlin.collections.List<Deal>>(
            localVariableConfig
        )
    }

    fun searchDealsRequestConfig(view: ViewSearchDeals, type: TypeSearchDeals, filter: kotlin.String, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, archiv: ArchivSearchDeals? = ArchivSearchDeals.NOTARCHIVED, sort: SortSearchDeals? = SortSearchDeals.LAST_MODIFIED, page: kotlin.Int? = 1, testOrder: TestOrderSearchDeals? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (lastUpdateDateFrom != null) {
                    put("lastUpdateDateFrom", listOf(lastUpdateDateFrom.toString()))
                }
                if (lastUpdateDateTo != null) {
                    put("lastUpdateDateTo", listOf(lastUpdateDateTo.toString()))
                }
                if (archiv != null) {
                    put("archiv", listOf(archiv.toString()))
                }
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (testOrder != null) {
                    put("testOrder", listOf(testOrder.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/xml, application/json"

        val params = mutableMapOf<String, Any>(
            "view" to view.value,
            "type" to type.value,
            "filter" to filter,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/business/deals/sales/search/{filter}/{view}.{type}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter view
     */
    enum class ViewSearchDeals1(val value: kotlin.String) {
        @JsonProperty(value = "deal") deal("deal")
    }

    /**
     * enum for parameter type
     */
    enum class TypeSearchDeals1(val value: kotlin.String) {
        @JsonProperty(value = "xml") xml("xml"),
        @JsonProperty(value = "json") json("json")
    }

    /**
     * enum for parameter businessType
     */
    enum class BusinessTypeSearchDeals1(val value: kotlin.String) {
        @JsonProperty(value = "PURCHASE") PURCHASE("PURCHASE"),
        @JsonProperty(value = "SALE") SALE("SALE")
    }

    /**
     * enum for parameter archiv
     */
    enum class ArchivSearchDeals1(val value: kotlin.String) {
        @JsonProperty(value = "ARCHIVED") ARCHIVED("ARCHIVED"),
        @JsonProperty(value = "NOTARCHIVED") NOTARCHIVED("NOTARCHIVED")
    }

    /**
     * enum for parameter sort
     */
    enum class SortSearchDeals1(val value: kotlin.String) {
        @JsonProperty(value = "LAST_MODIFIED") LAST_MODIFIED("LAST_MODIFIED"),
        @JsonProperty(value = "DATE_DESC") DATE_DESC("DATE_DESC"),
        @JsonProperty(value = "DATE_ASC") DATE_ASC("DATE_ASC"),
        @JsonProperty(value = "SUPPLIER") SUPPLIER("SUPPLIER"),
        @JsonProperty(value = "ID") ID("ID")
    }


    @Throws(WebClientResponseException::class)
    @Deprecated(message = "This operation is deprecated.")
    fun searchDeals1(view: ViewSearchDeals1, type: TypeSearchDeals1, filter: kotlin.String, businessType: BusinessTypeSearchDeals1, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, archiv: ArchivSearchDeals1? = ArchivSearchDeals1.NOTARCHIVED, sort: SortSearchDeals1? = SortSearchDeals1.LAST_MODIFIED, page: kotlin.Int? = 1): Mono<kotlin.collections.List<Deal>> {
        return searchDeals1WithHttpInfo(view = view, type = type, filter = filter, businessType = businessType, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, archiv = archiv, sort = sort, page = page)
            .map { it.body }
    }

    @Throws(WebClientResponseException::class)
    @Deprecated(message = "This operation is deprecated.")
    fun searchDeals1WithHttpInfo(view: ViewSearchDeals1, type: TypeSearchDeals1, filter: kotlin.String, businessType: BusinessTypeSearchDeals1, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, archiv: ArchivSearchDeals1? = ArchivSearchDeals1.NOTARCHIVED, sort: SortSearchDeals1? = SortSearchDeals1.LAST_MODIFIED, page: kotlin.Int? = 1): Mono<ResponseEntity<kotlin.collections.List<Deal>>> {
        val localVariableConfig = searchDeals1RequestConfig(view = view, type = type, filter = filter, businessType = businessType, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, archiv = archiv, sort = sort, page = page)
        return request<Unit, kotlin.collections.List<Deal>>(
            localVariableConfig
        )
    }

    @Deprecated(message = "This operation is deprecated.")
    fun searchDeals1RequestConfig(view: ViewSearchDeals1, type: TypeSearchDeals1, filter: kotlin.String, businessType: BusinessTypeSearchDeals1, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, archiv: ArchivSearchDeals1? = ArchivSearchDeals1.NOTARCHIVED, sort: SortSearchDeals1? = SortSearchDeals1.LAST_MODIFIED, page: kotlin.Int? = 1) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (lastUpdateDateFrom != null) {
                    put("lastUpdateDateFrom", listOf(lastUpdateDateFrom.toString()))
                }
                if (lastUpdateDateTo != null) {
                    put("lastUpdateDateTo", listOf(lastUpdateDateTo.toString()))
                }
                if (archiv != null) {
                    put("archiv", listOf(archiv.toString()))
                }
                put("businessType", listOf(businessType.toString()))
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/xml, application/json"

        val params = mutableMapOf<String, Any>(
            "view" to view.value,
            "type" to type.value,
            "filter" to filter,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/business/deals/search/{filter}/{view}.{type}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter view
     */
    enum class ViewSearchOrders(val value: kotlin.String) {
        @JsonProperty(value = "deal") deal("deal")
    }

    /**
     * enum for parameter type
     */
    enum class TypeSearchOrders(val value: kotlin.String) {
        @JsonProperty(value = "xml") xml("xml"),
        @JsonProperty(value = "json") json("json")
    }

    /**
     * enum for parameter archiv
     */
    enum class ArchivSearchOrders(val value: kotlin.String) {
        @JsonProperty(value = "ARCHIVED") ARCHIVED("ARCHIVED"),
        @JsonProperty(value = "NOTARCHIVED") NOTARCHIVED("NOTARCHIVED")
    }

    /**
     * enum for parameter sort
     */
    enum class SortSearchOrders(val value: kotlin.String) {
        @JsonProperty(value = "LAST_MODIFIED") LAST_MODIFIED("LAST_MODIFIED"),
        @JsonProperty(value = "DATE_DESC") DATE_DESC("DATE_DESC"),
        @JsonProperty(value = "DATE_ASC") DATE_ASC("DATE_ASC"),
        @JsonProperty(value = "SUPPLIER") SUPPLIER("SUPPLIER"),
        @JsonProperty(value = "ID") ID("ID")
    }


    @Throws(WebClientResponseException::class)
    fun searchOrders(view: ViewSearchOrders, type: TypeSearchOrders, filter: kotlin.String, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, archiv: ArchivSearchOrders? = ArchivSearchOrders.NOTARCHIVED, sort: SortSearchOrders? = SortSearchOrders.LAST_MODIFIED, page: kotlin.Int? = 1): Mono<kotlin.collections.List<Deal>> {
        return searchOrdersWithHttpInfo(view = view, type = type, filter = filter, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, archiv = archiv, sort = sort, page = page)
            .map { it.body }
    }

    @Throws(WebClientResponseException::class)
    fun searchOrdersWithHttpInfo(view: ViewSearchOrders, type: TypeSearchOrders, filter: kotlin.String, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, archiv: ArchivSearchOrders? = ArchivSearchOrders.NOTARCHIVED, sort: SortSearchOrders? = SortSearchOrders.LAST_MODIFIED, page: kotlin.Int? = 1): Mono<ResponseEntity<kotlin.collections.List<Deal>>> {
        val localVariableConfig = searchOrdersRequestConfig(view = view, type = type, filter = filter, lastUpdateDateFrom = lastUpdateDateFrom, lastUpdateDateTo = lastUpdateDateTo, archiv = archiv, sort = sort, page = page)
        return request<Unit, kotlin.collections.List<Deal>>(
            localVariableConfig
        )
    }

    fun searchOrdersRequestConfig(view: ViewSearchOrders, type: TypeSearchOrders, filter: kotlin.String, lastUpdateDateFrom: kotlin.String? = null, lastUpdateDateTo: kotlin.String? = null, archiv: ArchivSearchOrders? = ArchivSearchOrders.NOTARCHIVED, sort: SortSearchOrders? = SortSearchOrders.LAST_MODIFIED, page: kotlin.Int? = 1) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (lastUpdateDateFrom != null) {
                    put("lastUpdateDateFrom", listOf(lastUpdateDateFrom.toString()))
                }
                if (lastUpdateDateTo != null) {
                    put("lastUpdateDateTo", listOf(lastUpdateDateTo.toString()))
                }
                if (archiv != null) {
                    put("archiv", listOf(archiv.toString()))
                }
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/xml, application/json"

        val params = mutableMapOf<String, Any>(
            "view" to view.value,
            "type" to type.value,
            "filter" to filter,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/business/deals/purchase/search/{filter}/{view}.{type}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

}
